import { AUTH_ALLOW_NON_BIOMETRIC_SAVE, AUTH_CLIENT_ID, AUTH_CLIENT_SECRET, AUTH_ENDPOINT, AUTH_REDIRECT_URL, AUTH_REVOKE_URL, AUTH_SCOPES, AUTH_TOKEN_EXCHANGE_URL } from '@env'
// need to wrap @env for testing purposes
export default () => ({
	AUTH_ALLOW_NON_BIOMETRIC_SAVE,
	AUTH_CLIENT_SECRET,
	AUTH_CLIENT_ID,
	AUTH_REDIRECT_URL,
	AUTH_SCOPES,
	AUTH_ENDPOINT,
	AUTH_TOKEN_EXCHANGE_URL,
	AUTH_REVOKE_URL,
})
