type FlagT = {
  iso_code: string
  calling_code: number
  name: string
}
export const DefaultFlagCode = 'US'
export const Flags: Array<FlagT> = [
  { iso_code: 'AC', calling_code: 247, name: 'Ascension Island' },
  { iso_code: 'AD', calling_code: 376, name: 'Andorra' },
  { iso_code: 'AE', calling_code: 971, name: 'United Arab Emirates' },
  { iso_code: 'AF', calling_code: 93, name: 'Afghanistan' },
  { iso_code: 'AG', calling_code: 1, name: 'Antigua and Barbuda' },
  { iso_code: 'AI', calling_code: 1, name: 'Anguilla' },
  { iso_code: 'AL', calling_code: 355, name: 'Albania' },
  { iso_code: 'AM', calling_code: 374, name: 'Armenia' },
  { iso_code: 'AO', calling_code: 244, name: 'Angola' },
  { iso_code: 'AR', calling_code: 54, name: 'Argentina' },
  { iso_code: 'AS', calling_code: 1, name: 'American Samoa' },
  { iso_code: 'AT', calling_code: 43, name: 'Austria' },
  { iso_code: 'AU', calling_code: 61, name: 'Australia' },
  { iso_code: 'AW', calling_code: 297, name: 'Aruba' },
  { iso_code: 'AX', calling_code: 358, name: 'Åland Islands' },
  { iso_code: 'AZ', calling_code: 994, name: 'Azerbaijan' },
  { iso_code: 'BA', calling_code: 387, name: 'Bosnia and Herzegovina' },
  { iso_code: 'BB', calling_code: 1, name: 'Barbados' },
  { iso_code: 'BD', calling_code: 880, name: 'Bangladesh' },
  { iso_code: 'BE', calling_code: 32, name: 'Belgium' },
  { iso_code: 'BF', calling_code: 226, name: 'Burkina Faso' },
  { iso_code: 'BG', calling_code: 359, name: 'Bulgaria' },
  { iso_code: 'BH', calling_code: 973, name: 'Bahrain' },
  { iso_code: 'BI', calling_code: 257, name: 'Burundi' },
  { iso_code: 'BJ', calling_code: 229, name: 'Benin' },
  { iso_code: 'BL', calling_code: 590, name: 'Saint Barthélemy' },
  { iso_code: 'BM', calling_code: 1, name: 'Bermuda' },
  { iso_code: 'BN', calling_code: 673, name: 'Brunei' },
  { iso_code: 'BO', calling_code: 591, name: 'Bolivia' },
  { iso_code: 'BQ', calling_code: 599, name: 'Bonaire, Sint Eustatius and Saba' },
  { iso_code: 'BR', calling_code: 55, name: 'Brazil' },
  { iso_code: 'BS', calling_code: 1, name: 'Bahamas' },
  { iso_code: 'BT', calling_code: 975, name: 'Bhutan' },
  { iso_code: 'BW', calling_code: 267, name: 'Botswana' },
  { iso_code: 'BY', calling_code: 375, name: 'Belarus' },
  { iso_code: 'BZ', calling_code: 501, name: 'Belize' },
  { iso_code: 'CA', calling_code: 1, name: 'Canada' },
  { iso_code: 'CC', calling_code: 61, name: 'Cocos (Keeling) Islands' },
  { iso_code: 'CD', calling_code: 243, name: 'Congo, Democratic Republic of the' },
  { iso_code: 'CF', calling_code: 236, name: 'Central African Republic' },
  { iso_code: 'CG', calling_code: 242, name: 'Congo' },
  { iso_code: 'CH', calling_code: 41, name: 'Switzerland' },
  { iso_code: 'CI', calling_code: 225, name: 'Côte d’Ivoire' },
  { iso_code: 'CK', calling_code: 682, name: 'Cook Islands' },
  { iso_code: 'CL', calling_code: 56, name: 'Chile' },
  { iso_code: 'CM', calling_code: 237, name: 'Cameroon' },
  { iso_code: 'CN', calling_code: 86, name: 'China' },
  { iso_code: 'CO', calling_code: 57, name: 'Colombia' },
  { iso_code: 'CR', calling_code: 506, name: 'Costa Rica' },
  { iso_code: 'CU', calling_code: 53, name: 'Cuba' },
  { iso_code: 'CV', calling_code: 238, name: 'Cape Verde' },
  { iso_code: 'CW', calling_code: 599, name: 'Curaçao' },
  { iso_code: 'CX', calling_code: 61, name: 'Christmas Island' },
  { iso_code: 'CY', calling_code: 357, name: 'Cyprus' },
  { iso_code: 'CZ', calling_code: 420, name: 'Czechia' },
  { iso_code: 'DE', calling_code: 49, name: 'Germany' },
  { iso_code: 'DJ', calling_code: 253, name: 'Djibouti' },
  { iso_code: 'DK', calling_code: 45, name: 'Denmark' },
  { iso_code: 'DM', calling_code: 1, name: 'Dominica' },
  { iso_code: 'DO', calling_code: 1, name: 'Dominican Republic' },
  { iso_code: 'DZ', calling_code: 213, name: 'Algeria' },
  { iso_code: 'EC', calling_code: 593, name: 'Ecuador' },
  { iso_code: 'EE', calling_code: 372, name: 'Estonia' },
  { iso_code: 'EG', calling_code: 20, name: 'Egypt' },
  { iso_code: 'EH', calling_code: 212, name: 'Western Sahara' },
  { iso_code: 'ER', calling_code: 291, name: 'Eritrea' },
  { iso_code: 'ES', calling_code: 34, name: 'Spain' },
  { iso_code: 'ET', calling_code: 251, name: 'Ethiopia' },
  { iso_code: 'FI', calling_code: 358, name: 'Finland' },
  { iso_code: 'FJ', calling_code: 679, name: 'Fiji' },
  { iso_code: 'FK', calling_code: 500, name: 'Falkland Islands (Malvinas)' },
  { iso_code: 'FM', calling_code: 691, name: 'Micronesia' },
  { iso_code: 'FO', calling_code: 298, name: 'Faroe Islands' },
  { iso_code: 'FR', calling_code: 33, name: 'France' },
  { iso_code: 'GA', calling_code: 241, name: 'Gabon' },
  { iso_code: 'GB', calling_code: 44, name: 'United Kingdom' },
  { iso_code: 'GD', calling_code: 1, name: 'Grenada' },
  { iso_code: 'GE', calling_code: 995, name: 'Georgia' },
  { iso_code: 'GF', calling_code: 594, name: 'French Guiana' },
  { iso_code: 'GG', calling_code: 44, name: 'Guernsey' },
  { iso_code: 'GH', calling_code: 233, name: 'Ghana' },
  { iso_code: 'GI', calling_code: 350, name: 'Gibraltar' },
  { iso_code: 'GL', calling_code: 299, name: 'Greenland' },
  { iso_code: 'GM', calling_code: 220, name: 'Gambia' },
  { iso_code: 'GN', calling_code: 224, name: 'Guinea' },
  { iso_code: 'GP', calling_code: 590, name: 'Guadeloupe' },
  { iso_code: 'GQ', calling_code: 240, name: 'Equatorial Guinea' },
  { iso_code: 'GR', calling_code: 30, name: 'Greece' },
  { iso_code: 'GT', calling_code: 502, name: 'Guatemala' },
  { iso_code: 'GU', calling_code: 1, name: 'Guam' },
  { iso_code: 'GW', calling_code: 245, name: 'Guinea-Bissau' },
  { iso_code: 'GY', calling_code: 592, name: 'Guyana' },
  { iso_code: 'HK', calling_code: 852, name: 'Hong Kong' },
  { iso_code: 'HN', calling_code: 504, name: 'Honduras' },
  { iso_code: 'HR', calling_code: 385, name: 'Croatia' },
  { iso_code: 'HT', calling_code: 509, name: 'Haiti' },
  { iso_code: 'HU', calling_code: 36, name: 'Hungary' },
  { iso_code: 'ID', calling_code: 62, name: 'Indonesia' },
  { iso_code: 'IE', calling_code: 353, name: 'Ireland' },
  { iso_code: 'IL', calling_code: 972, name: 'Israel' },
  { iso_code: 'IM', calling_code: 44, name: 'Isle of Man' },
  { iso_code: 'IN', calling_code: 91, name: 'India' },
  { iso_code: 'IO', calling_code: 246, name: 'British Indian Ocean Territory' },
  { iso_code: 'IQ', calling_code: 964, name: 'Iraq' },
  { iso_code: 'IR', calling_code: 98, name: 'Iran' },
  { iso_code: 'IS', calling_code: 354, name: 'Iceland' },
  { iso_code: 'IT', calling_code: 39, name: 'Italy' },
  { iso_code: 'JE', calling_code: 44, name: 'Jersey' },
  { iso_code: 'JM', calling_code: 1, name: 'Jamaica' },
  { iso_code: 'JO', calling_code: 962, name: 'Jordan' },
  { iso_code: 'JP', calling_code: 81, name: 'Japan' },
  { iso_code: 'KE', calling_code: 254, name: 'Kenya' },
  { iso_code: 'KG', calling_code: 996, name: 'Kyrgyzstan' },
  { iso_code: 'KH', calling_code: 855, name: 'Cambodia' },
  { iso_code: 'KI', calling_code: 686, name: 'Kiribati' },
  { iso_code: 'KM', calling_code: 269, name: 'Comoros' },
  { iso_code: 'KN', calling_code: 1, name: 'Saint Kitts and Nevis' },
  { iso_code: 'KP', calling_code: 850, name: "Korea, Democratic People's Republic of" },
  { iso_code: 'KR', calling_code: 82, name: 'Korea, Republic of' },
  { iso_code: 'KW', calling_code: 965, name: 'Kuwait' },
  { iso_code: 'KY', calling_code: 1, name: 'Cayman Islands' },
  { iso_code: 'KZ', calling_code: 7, name: 'Kazakhstan' },
  { iso_code: 'LA', calling_code: 856, name: 'Laos' },
  { iso_code: 'LB', calling_code: 961, name: 'Lebanon' },
  { iso_code: 'LC', calling_code: 1, name: 'Saint Lucia' },
  { iso_code: 'LI', calling_code: 423, name: 'Liechtenstein' },
  { iso_code: 'LK', calling_code: 94, name: 'Sri Lanka' },
  { iso_code: 'LR', calling_code: 231, name: 'Liberia' },
  { iso_code: 'LS', calling_code: 266, name: 'Lesotho' },
  { iso_code: 'LT', calling_code: 370, name: 'Lithuania' },
  { iso_code: 'LU', calling_code: 352, name: 'Luxembourg' },
  { iso_code: 'LV', calling_code: 371, name: 'Latvia' },
  { iso_code: 'LY', calling_code: 218, name: 'Libya' },
  { iso_code: 'MA', calling_code: 212, name: 'Morocco' },
  { iso_code: 'MC', calling_code: 377, name: 'Monaco' },
  { iso_code: 'MD', calling_code: 373, name: 'Moldova, Republic of' },
  { iso_code: 'ME', calling_code: 382, name: 'Montenegro' },
  { iso_code: 'MF', calling_code: 590, name: 'Saint Martin (French part)' },
  { iso_code: 'MG', calling_code: 261, name: 'Madagascar' },
  { iso_code: 'MH', calling_code: 692, name: 'Marshall Islands' },
  { iso_code: 'MK', calling_code: 389, name: 'North Macedonia' },
  { iso_code: 'ML', calling_code: 223, name: 'Mali' },
  { iso_code: 'MM', calling_code: 95, name: 'Myanmar' },
  { iso_code: 'MN', calling_code: 976, name: 'Mongolia' },
  { iso_code: 'MO', calling_code: 853, name: 'Macao' },
  { iso_code: 'MP', calling_code: 1, name: 'Northern Mariana Islands' },
  { iso_code: 'MQ', calling_code: 596, name: 'Martinique' },
  { iso_code: 'MR', calling_code: 222, name: 'Mauritania' },
  { iso_code: 'MS', calling_code: 1, name: 'Montserrat' },
  { iso_code: 'MT', calling_code: 356, name: 'Malta' },
  { iso_code: 'MU', calling_code: 230, name: 'Mauritius' },
  { iso_code: 'MV', calling_code: 960, name: 'Maldives' },
  { iso_code: 'MW', calling_code: 265, name: 'Malawi' },
  { iso_code: 'MX', calling_code: 52, name: 'Mexico' },
  { iso_code: 'MY', calling_code: 60, name: 'Malaysia' },
  { iso_code: 'MZ', calling_code: 258, name: 'Mozambique' },
  { iso_code: 'NA', calling_code: 264, name: 'Namibia' },
  { iso_code: 'NC', calling_code: 687, name: 'New Caledonia' },
  { iso_code: 'NE', calling_code: 227, name: 'Niger' },
  { iso_code: 'NF', calling_code: 672, name: 'Norfolk Island' },
  { iso_code: 'NG', calling_code: 234, name: 'Nigeria' },
  { iso_code: 'NI', calling_code: 505, name: 'Nicaragua' },
  { iso_code: 'NL', calling_code: 31, name: 'Netherlands' },
  { iso_code: 'NO', calling_code: 47, name: 'Norway' },
  { iso_code: 'NP', calling_code: 977, name: 'Nepal' },
  { iso_code: 'NR', calling_code: 674, name: 'Nauru' },
  { iso_code: 'NU', calling_code: 683, name: 'Niue' },
  { iso_code: 'NZ', calling_code: 64, name: 'New Zealand' },
  { iso_code: 'OM', calling_code: 968, name: 'Oman' },
  { iso_code: 'PA', calling_code: 507, name: 'Panama' },
  { iso_code: 'PE', calling_code: 51, name: 'Peru' },
  { iso_code: 'PF', calling_code: 689, name: 'French Polynesia' },
  { iso_code: 'PG', calling_code: 675, name: 'Papua New Guinea' },
  { iso_code: 'PH', calling_code: 63, name: 'Philippines' },
  { iso_code: 'PK', calling_code: 92, name: 'Pakistan' },
  { iso_code: 'PL', calling_code: 48, name: 'Poland' },
  { iso_code: 'PM', calling_code: 508, name: 'Saint Pierre and Miquelon' },
  { iso_code: 'PR', calling_code: 1, name: 'Puerto Rico' },
  { iso_code: 'PS', calling_code: 970, name: 'Palestine' },
  { iso_code: 'PT', calling_code: 351, name: 'Portugal' },
  { iso_code: 'PW', calling_code: 680, name: 'Palau' },
  { iso_code: 'PY', calling_code: 595, name: 'Paraguay' },
  { iso_code: 'QA', calling_code: 974, name: 'Qatar' },
  { iso_code: 'RE', calling_code: 262, name: 'Réunion' },
  { iso_code: 'RO', calling_code: 40, name: 'Romania' },
  { iso_code: 'RS', calling_code: 381, name: 'Serbia' },
  { iso_code: 'RU', calling_code: 7, name: 'Russian Federation' },
  { iso_code: 'RW', calling_code: 250, name: 'Rwanda' },
  { iso_code: 'SA', calling_code: 966, name: 'Saudi Arabia' },
  { iso_code: 'SB', calling_code: 677, name: 'Solomon Islands' },
  { iso_code: 'SC', calling_code: 248, name: 'Seychelles' },
  { iso_code: 'SD', calling_code: 249, name: 'Sudan' },
  { iso_code: 'SE', calling_code: 46, name: 'Sweden' },
  { iso_code: 'SG', calling_code: 65, name: 'Singapore' },
  { iso_code: 'SH', calling_code: 290, name: 'Saint Helena, Ascension and Tristan da Cunha' },
  { iso_code: 'SI', calling_code: 386, name: 'Slovenia' },
  { iso_code: 'SJ', calling_code: 47, name: 'Svalbard and Jan Mayen' },
  { iso_code: 'SK', calling_code: 421, name: 'Slovakia' },
  { iso_code: 'SL', calling_code: 232, name: 'Sierra Leone' },
  { iso_code: 'SM', calling_code: 378, name: 'San Marino' },
  { iso_code: 'SN', calling_code: 221, name: 'Senegal' },
  { iso_code: 'SO', calling_code: 252, name: 'Somalia' },
  { iso_code: 'SR', calling_code: 597, name: 'Suriname' },
  { iso_code: 'SS', calling_code: 211, name: 'South Sudan' },
  { iso_code: 'ST', calling_code: 239, name: 'São Tomé and Príncipe' },
  { iso_code: 'SV', calling_code: 503, name: 'El Salvador' },
  { iso_code: 'SX', calling_code: 1, name: 'Sint Maarten (Dutch part)' },
  { iso_code: 'SY', calling_code: 963, name: 'Syrian Arab Republic' },
  { iso_code: 'SZ', calling_code: 268, name: 'Eswatini' },
  { iso_code: 'TA', calling_code: 290, name: 'Tristan da Cunha' },
  { iso_code: 'TC', calling_code: 1, name: 'Turks and Caicos Islands' },
  { iso_code: 'TD', calling_code: 235, name: 'Chad' },
  { iso_code: 'TG', calling_code: 228, name: 'Togo' },
  { iso_code: 'TH', calling_code: 66, name: 'Thailand' },
  { iso_code: 'TJ', calling_code: 992, name: 'Tajikistan' },
  { iso_code: 'TK', calling_code: 690, name: 'Tokelau' },
  { iso_code: 'TL', calling_code: 670, name: 'Timor-Leste' },
  { iso_code: 'TM', calling_code: 993, name: 'Turkmenistan' },
  { iso_code: 'TN', calling_code: 216, name: 'Tunisia' },
  { iso_code: 'TO', calling_code: 676, name: 'Tonga' },
  { iso_code: 'TR', calling_code: 90, name: 'Türkiye' },
  { iso_code: 'TT', calling_code: 1, name: 'Trinidad and Tobago' },
  { iso_code: 'TV', calling_code: 688, name: 'Tuvalu' },
  { iso_code: 'TW', calling_code: 886, name: 'Taiwan' },
  { iso_code: 'TZ', calling_code: 255, name: 'Tanzania' },
  { iso_code: 'UA', calling_code: 380, name: 'Ukraine' },
  { iso_code: 'UG', calling_code: 256, name: 'Uganda' },
  { iso_code: 'US', calling_code: 1, name: 'United States of America' },
  { iso_code: 'UY', calling_code: 598, name: 'Uruguay' },
  { iso_code: 'UZ', calling_code: 998, name: 'Uzbekistan' },
  { iso_code: 'VA', calling_code: 39, name: 'Holy See' },
  { iso_code: 'VC', calling_code: 1, name: 'Saint Vincent and the Grenadines' },
  { iso_code: 'VE', calling_code: 58, name: 'Venezuela' },
  { iso_code: 'VG', calling_code: 1, name: 'British Virgin Islands' },
  { iso_code: 'VI', calling_code: 1, name: 'Virgin Islands (U.S.)' },
  { iso_code: 'VN', calling_code: 84, name: 'Viet Nam' },
  { iso_code: 'VU', calling_code: 678, name: 'Vanuatu' },
  { iso_code: 'WF', calling_code: 681, name: 'Wallis and Futuna' },
  { iso_code: 'WS', calling_code: 685, name: 'Samoa' },
  { iso_code: 'XK', calling_code: 383, name: 'Kosovo' },
  { iso_code: 'YE', calling_code: 967, name: 'Yemen' },
  { iso_code: 'YT', calling_code: 262, name: 'Mayotte' },
  { iso_code: 'ZA', calling_code: 27, name: 'South Africa' },
  { iso_code: 'ZM', calling_code: 260, name: 'Zambia' },
  { iso_code: 'ZW', calling_code: 263, name: 'Zimbabwe' },
  { iso_code: 'GS', calling_code: 500, name: 'South Georgia and South Sandwich Islands' },
  { iso_code: 'AQ', calling_code: 672, name: 'Antarctica' },
  { iso_code: 'BV', calling_code: 47, name: 'Bouvet Island' },
  { iso_code: 'TF', calling_code: 262, name: 'French Southern Territories' },
  { iso_code: 'HM', calling_code: 61, name: 'Heard and McDonald Islands' },
  { iso_code: 'UM', calling_code: 1, name: 'United States Minor Outlying Islands' },
  { iso_code: 'PN', calling_code: 64, name: 'Pitcairn' },
]
