/**
 * ReleaseNotesHistory Component
 *
 * This component renders a historical log of App Store release notes.
 * It consumes a flattened JSON history generated by the `fetchWhatsNewData.js` scraper.
 */
import * as React from 'react'

import data from '@site/static/data/whats-new-history.json'

interface ReleaseEntry {
  version: string
  releaseDate: string
  releaseNotes?: string | null
}

/**
 * Renders the App Store Release Notes block.
 */
const ReleaseNotesSection = ({ notes }: { notes: string }) => {
  return (
    <div className="alert alert--info margin-bottom--lg">
      <h3 className="margin-bottom--sm text--bold">Release Notes</h3>
      <div
        style={{
          lineHeight: '1.6',
          whiteSpace: 'pre-line',
        }}>
        {notes}
      </div>
    </div>
  )
}

const ReleaseNotesHistory = () => {
  const history = data as unknown as ReleaseEntry[]
  const releaseNotesHistory = history.filter((release) => !!release.releaseNotes)

  return (
    <div className="container margin-vert--lg">
      {releaseNotesHistory.map((release, index) => (
        <div key={`rn-${index}`} className="margin-bottom--xl">
          <div className="margin-bottom--md">
            <h3 className="text--primary margin-bottom--xs">{release.version}</h3>
            <div className="font-weight--medium margin-bottom--sm">
              Released on: {new Date(release.releaseDate).toLocaleDateString()}
            </div>
          </div>

          {release.releaseNotes && <ReleaseNotesSection notes={release.releaseNotes} />}
        </div>
      ))}
    </div>
  )
}

export default ReleaseNotesHistory
