/**
 * WhatsNewReport Component
 *
 * This component renders a historical timeline of app features and release notes.
 * It consumes a flattened JSON history generated by the `fetchWhatsNewData.js` scraper,
 * merges it with any manual overrides, and displays it in a clean, sorted list.
 *
 * Each release section includes:
 * - Version and Release Date
 * - "What's New" feature highlights (title, bullets, and optional links)
 * - App Store Release Notes (formatted for readability)
 */
import * as React from 'react'

import data from '@site/static/data/whats-new-history.json'

/**
 * TYPES & INTERFACES
 */

interface FeatureContent {
  featureId?: string // Link to technical tracking (e.g., 'TravelListAndStatus' or '2.65')
  title: string // The primary descriptive sentence
  bullets: string[] // Optional supporting details
  link: { text: string; url: string } // Optional 'Learn More' action
}

/**
 * Represents a single app release entry in the historical log.
 */
interface ReleaseEntry {
  version: string
  releaseDate: string
  releaseNotes?: string | null
  whatsNew: FeatureContent[]
}

/**
 * SHARED STYLES
 */
const COLORS = {
  primary: '#003e67', // Dark Blue
  secondary: '#0071bb', // Light Blue
  text: '#1a1a1a',
  textSecondary: '#444',
  textMuted: '#666',
  background: '#f8f9fa',
  border: '#eaebec',
}

const STYLES = {
  CONTAINER: {
    marginBottom: '2rem',
    marginLeft: '1rem',
    padding: '1.25rem',
    backgroundColor: COLORS.background,
    borderRadius: '12px',
    boxShadow: '0 2px 4px rgba(0,0,0,0.05)',
  },
  SECTION_HEADER: {
    fontSize: '0.9rem',
    fontWeight: 700,
    marginBottom: '0.75rem',
    textTransform: 'uppercase' as const,
    letterSpacing: '1.5px',
  },
  LIST: {
    marginBottom: '1rem',
    paddingLeft: '1.5rem',
    color: COLORS.textSecondary,
  },
  LIST_ITEM: {
    marginBottom: '0.4rem',
  },
}

/**
 * MANUAL OVERRIDES
 * Use this array to manually insert or correct records that the automated
 * script cannot resolve from Git tags.
 */
const MANUAL_ENTRIES: ReleaseEntry[] = []

/**
 * Merges automated history data with manual overrides, deduplicates by version,
 * and sorts them in descending SemVer order.
 *
 * @param history - The JSON data generated by fetchWhatsNewData.js
 * @param manual - Any manual overrides defined in MANUAL_ENTRIES
 */
const getSortedUnifiedHistory = (history: ReleaseEntry[], manual: ReleaseEntry[]) => {
  const combined = [...history, ...manual]

  const groupedByVersion = combined.reduce(
    (acc, item) => {
      const { version, releaseDate, whatsNew, releaseNotes } = item
      const existing = acc[version]

      if (!existing) {
        acc[version] = { ...item, whatsNew: [...whatsNew] }
      } else {
        existing.whatsNew = [...existing.whatsNew, ...whatsNew]
        existing.releaseNotes = releaseNotes || existing.releaseNotes
        // Keep the latest release date for the version
        if (new Date(releaseDate) > new Date(existing.releaseDate)) {
          existing.releaseDate = releaseDate
        }
      }
      return acc
    },
    {} as Record<string, ReleaseEntry>,
  )

  return Object.values(groupedByVersion).sort((a, b) => {
    const v1 = a.version.replace(/^v/, '').split('.').map(Number)
    const v2 = b.version.replace(/^v/, '').split('.').map(Number)
    for (let i = 0; i < Math.max(v1.length, v2.length); i++) {
      const p1 = v1[i] || 0
      const p2 = v2[i] || 0
      if (p1 !== p2) return p2 - p1
    }
    return 0
  })
}

/**
 * SUB-COMPONENTS
 */

/**
 * Renders the App Store Release Notes block.
 */
const ReleaseNotesSection = ({ notes }: { notes: string }) => {
  const lines = notes.split('\n')
  const content: React.ReactNode[] = []
  let currentList: string[] = []

  const flushList = (key: string) => {
    if (currentList.length > 0) {
      content.push(
        <ul key={key} style={STYLES.LIST}>
          {currentList.map((item, i) => (
            <li key={i} style={STYLES.LIST_ITEM}>
              {item}
            </li>
          ))}
        </ul>,
      )
      currentList = []
    }
  }

  lines.forEach((line, index) => {
    const trimmed = line.trim()
    if (trimmed.startsWith('-')) {
      currentList.push(trimmed.slice(1).trim())
    } else {
      flushList(`list-before-${index}`)
      if (trimmed) {
        content.push(
          <p key={index} style={{ marginBottom: '1rem', color: COLORS.textSecondary }}>
            {trimmed}
          </p>,
        )
      }
    }
  })
  flushList('list-final')

  return (
    <div style={{ ...STYLES.CONTAINER, borderLeft: `5px solid ${COLORS.primary}` }}>
      <h3 style={{ ...STYLES.SECTION_HEADER, color: COLORS.primary }}>Release Notes</h3>
      <div style={{ lineHeight: '1.6', fontSize: '1rem' }}>{content}</div>
    </div>
  )
}

/**
 * Renders a single "What's New" feature entry.
 */
const WhatsNewSection = ({ feature }: { feature: FeatureContent }) => {
  return (
    <div style={{ ...STYLES.CONTAINER, borderLeft: `5px solid ${COLORS.secondary}` }}>
      <h3 style={{ ...STYLES.SECTION_HEADER, color: COLORS.secondary }}>What's New</h3>
      <p style={{ marginBottom: '0.75rem', color: COLORS.text }}>{feature.title}</p>
      {feature.bullets.length > 0 && (
        <ul style={STYLES.LIST}>
          {feature.bullets.map((bullet, i) => (
            <li key={i} style={STYLES.LIST_ITEM}>
              {bullet}
            </li>
          ))}
        </ul>
      )}
      {feature.link.url && (
        <div style={{ marginTop: '0.5rem' }}>
          <a href={feature.link.url} target="_blank" rel="noopener noreferrer">
            {feature.link.text || 'View details online'} →
          </a>
        </div>
      )}
    </div>
  )
}

/**
 * MAIN COMPONENT
 */

const WhatsNewReport = () => {
  const unifiedHistory = React.useMemo(() => {
    return getSortedUnifiedHistory(data as unknown as ReleaseEntry[], MANUAL_ENTRIES)
  }, [])

  return (
    <div style={{ maxWidth: '900px', margin: '0 auto', fontFamily: 'inherit' }}>
      {unifiedHistory.map((release, index) => (
        <div
          key={index}
          style={{ marginBottom: '4rem', borderBottom: `2px solid ${COLORS.border}`, paddingBottom: '2rem' }}>
          <div style={{ marginBottom: '1.5rem' }}>
            <h2 style={{ color: COLORS.primary, fontSize: '2rem', margin: 0 }}>{release.version}</h2>
            <div style={{ color: COLORS.textMuted, fontSize: '0.95rem', fontWeight: 500, marginTop: '0.25rem' }}>
              Released on: {new Date(release.releaseDate).toLocaleDateString()}
            </div>
          </div>

          {release.whatsNew.map((feature, fIndex) => (
            <WhatsNewSection key={fIndex} feature={feature} />
          ))}

          {release.releaseNotes && <ReleaseNotesSection notes={release.releaseNotes} />}
        </div>
      ))}
    </div>
  )
}

export default WhatsNewReport
