/**
 * WhatsNewReport Component
 *
 * This component renders a historical timeline of app features and release notes.
 * It consumes a flattened JSON history generated by the `fetchWhatsNewData.js` scraper
 * and displays it in a clean, sorted list.
 *
 * Each release section includes:
 * - Version and Release Date
 * - "What's New" feature highlights (title, bullets, and optional links)
 * - App Store Release Notes (formatted for readability)
 */
import * as React from 'react'

import data from '@site/static/data/whats-new-history.json'

/**
 * TYPES & INTERFACES
 */

interface FeatureContent {
  featureId?: string // Feature or version identifier (e.g., 'TravelListAndStatus' or '2.65')
  title: string // The primary descriptive sentence
  bullets: string[] // Optional supporting details
  link: { text: string; url: string } // Optional 'Learn More' action
}

/**
 * Represents a single app release entry in the historical log.
 */
interface ReleaseEntry {
  version: string
  releaseDate: string
  releaseNotes?: string | null
  whatsNew: FeatureContent[]
}

/**
 * SHARED STYLES
 */
const COLORS = {
  primary: '#003e67', // Dark Blue
  secondary: '#0071bb', // Light Blue
  text: '#1a1a1a',
  textSecondary: '#444',
  textMuted: '#666',
  background: '#f8f9fa',
  border: '#eaebec',
}

const STYLES = {
  CONTAINER: {
    marginBottom: '2rem',
    marginLeft: '1rem',
    padding: '1.25rem',
    backgroundColor: COLORS.background,
    borderRadius: '12px',
    boxShadow: '0 2px 4px rgba(0,0,0,0.05)',
  },
  SECTION_HEADER: {
    fontSize: '0.9rem',
    fontWeight: 700,
    marginBottom: '0.75rem',
    textTransform: 'uppercase' as const,
    letterSpacing: '1.5px',
  },
  LIST: {
    marginBottom: '1rem',
    paddingLeft: '1.5rem',
    color: COLORS.textSecondary,
  },
  LIST_ITEM: {
    marginBottom: '0.4rem',
  },
}

/**
 * SUB-COMPONENTS
 */

/**
 * Renders the App Store Release Notes block.
 */
const ReleaseNotesSection = ({ notes }: { notes: string }) => {
  return (
    <div style={{ ...STYLES.CONTAINER, borderLeft: `5px solid ${COLORS.primary}` }}>
      <h3 style={{ ...STYLES.SECTION_HEADER, color: COLORS.primary }}>Release Notes</h3>
      <div
        style={{
          lineHeight: '1.6',
          fontSize: '1rem',
          color: COLORS.textSecondary,
          whiteSpace: 'pre-line',
        }}>
        {notes}
      </div>
    </div>
  )
}

/**
 * Renders a single "What's New" feature entry.
 */
const WhatsNewSection = ({ feature }: { feature: FeatureContent }) => {
  return (
    <div style={{ ...STYLES.CONTAINER, borderLeft: `5px solid ${COLORS.secondary}` }}>
      <h3 style={{ ...STYLES.SECTION_HEADER, color: COLORS.secondary }}>What's New</h3>
      <p style={{ marginBottom: '0.75rem', color: COLORS.text }}>{feature.title}</p>
      {feature.bullets.length > 0 && (
        <ul style={STYLES.LIST}>
          {feature.bullets.map((bullet, i) => (
            <li key={i} style={STYLES.LIST_ITEM}>
              {bullet}
            </li>
          ))}
        </ul>
      )}
      {feature.link.url && (
        <div style={{ marginTop: '0.5rem' }}>
          <a href={feature.link.url} target="_blank" rel="noopener noreferrer">
            {feature.link.text || 'View details online'} →
          </a>
        </div>
      )}
    </div>
  )
}

/**
 * MAIN COMPONENT
 */

const WhatsNewReport = () => {
  const history = data as unknown as ReleaseEntry[]

  return (
    <div style={{ maxWidth: '900px', margin: '0 auto', fontFamily: 'inherit' }}>
      {history.map((release, index) => (
        <div
          key={index}
          style={{ marginBottom: '4rem', borderBottom: `2px solid ${COLORS.border}`, paddingBottom: '2rem' }}>
          <div style={{ marginBottom: '1.5rem' }}>
            <h2 style={{ color: COLORS.primary, fontSize: '2rem', margin: 0 }}>{release.version}</h2>
            <div style={{ color: COLORS.textMuted, fontSize: '0.95rem', fontWeight: 500, marginTop: '0.25rem' }}>
              Released on: {new Date(release.releaseDate).toLocaleDateString()}
            </div>
          </div>

          {release.whatsNew.map((feature, fIndex) => (
            <WhatsNewSection key={fIndex} feature={feature} />
          ))}

          {release.releaseNotes && <ReleaseNotesSection notes={release.releaseNotes} />}
        </div>
      ))}
    </div>
  )
}

export default WhatsNewReport
