/**
 * WhatsNewReport Component
 *
 * This component renders a historical timeline of app features and release notes.
 * It consumes a flattened JSON history generated by the `fetchWhatsNewData.js` scraper
 * and displays it in a clean, sorted list.
 *
 * Each release section includes:
 * - Version and Release Date
 * - "What's New" feature highlights (title, bullets, and optional links)
 * - App Store Release Notes (formatted for readability)
 */
import * as React from 'react'

import data from '@site/static/data/whats-new-history.json'

/**
 * TYPES & INTERFACES
 */

interface FeatureContent {
  featureId?: string // Feature or version identifier (e.g., 'TravelListAndStatus' or '2.65')
  title: string // The primary descriptive sentence
  bullets: string[] // Optional supporting details
  link: { text: string; url: string } // Optional 'Learn More' action
}

/**
 * Represents a single app release entry in the historical log.
 */
interface ReleaseEntry {
  version: string
  releaseDate: string
  releaseNotes?: string | null
  whatsNew: FeatureContent[]
}

/**
 * SHARED STYLES
 * We use Infima (Docusaurus's CSS framework) classes for consistency.
 */
/**
 * SUB-COMPONENTS
 */

/**
 * Renders the App Store Release Notes block.
 */
const ReleaseNotesSection = ({ notes }: { notes: string }) => {
  return (
    <div className="alert alert--info margin-bottom--lg">
      <h3 className="margin-bottom--sm text--bold">Release Notes</h3>
      <div
        style={{
          lineHeight: '1.6',
          whiteSpace: 'pre-line',
        }}>
        {notes}
      </div>
    </div>
  )
}

/**
 * Renders a single "What's New" feature entry.
 */
const WhatsNewSection = ({ feature }: { feature: FeatureContent }) => {
  return (
    <div className="alert alert--warning margin-bottom--lg">
      <h3 className="margin-bottom--sm text--bold">What's New</h3>
      <p className="margin-bottom--sm">{feature.title}</p>
      {feature.bullets.length > 0 && (
        <ul className="margin-top--sm">
          {feature.bullets.map((bullet, i) => (
            <li key={i} className="margin-bottom--xs">
              {bullet}
            </li>
          ))}
        </ul>
      )}
      {feature.link.url && (
        <div className="margin-top--sm">
          <a
            href={feature.link.url}
            target="_blank"
            rel="noopener noreferrer"
            className="button button--link button--sm padding-left--none">
            {feature.link.text || 'View details online'} →
          </a>
        </div>
      )}
    </div>
  )
}

/**
 * MAIN COMPONENT
 */

const WhatsNewReport = () => {
  const history = data as unknown as ReleaseEntry[]

  return (
    <div className="container margin-vert--lg">
      {history.map((release, index) => (
        <div key={index} className="margin-bottom--lg padding-bottom--lg border-bottom">
          <div className="margin-bottom--md">
            <h2 className="text--primary margin-bottom--xs">{release.version}</h2>
            <div className="font-weight--medium margin-bottom--lg">
              Released on: {new Date(release.releaseDate).toLocaleDateString()}
            </div>
          </div>

          {release.whatsNew.map((feature, fIndex) => (
            <WhatsNewSection key={fIndex} feature={feature} />
          ))}

          {release.releaseNotes && <ReleaseNotesSection notes={release.releaseNotes} />}
        </div>
      ))}
    </div>
  )
}

export default WhatsNewReport
