/**
 * WhatsNewHistory Component
 *
 * This component renders a historical timeline of app feature highlights.
 * It consumes a flattened JSON history generated by the `fetchWhatsNewData.js` scraper.
 */
import * as React from 'react'

import data from '@site/static/data/whats-new-history.json'

interface FeatureContent {
  featureId?: string
  title: string
  bullets: string[]
  link: { text: string; url: string }
}

interface ReleaseEntry {
  version: string
  releaseDate: string
  releaseNotes?: string | null
  whatsNew: FeatureContent[]
}

/**
 * Renders a single "What's New" feature entry.
 */
const WhatsNewSection = ({ feature }: { feature: FeatureContent }) => {
  return (
    <div className="alert alert--warning margin-bottom--lg">
      <h3 className="margin-bottom--sm text--bold">What's New</h3>
      <p className="margin-bottom--sm">{feature.title}</p>
      {feature.bullets.length > 0 && (
        <ul className="margin-top--sm">
          {feature.bullets.map((bullet, i) => (
            <li key={i} className="margin-bottom--xs">
              {bullet}
            </li>
          ))}
        </ul>
      )}
      {feature.link.url && (
        <div className="margin-top--sm">
          <a
            href={feature.link.url}
            target="_blank"
            rel="noopener noreferrer"
            className="button button--link button--sm padding-left--none">
            {feature.link.text || 'View details online'} →
          </a>
        </div>
      )}
    </div>
  )
}

const WhatsNewHistory = () => {
  const history = data as unknown as ReleaseEntry[]
  const whatsNewHistory = history.filter((release) => release.whatsNew.length > 0)

  return (
    <div className="container margin-vert--lg">
      {whatsNewHistory.map((release, index) => (
        <div key={`wn-${index}`} className="margin-bottom--xl">
          <div className="margin-bottom--md">
            <h3 className="text--primary margin-bottom--xs">{release.version}</h3>
            <div className="font-weight--medium margin-bottom--sm">
              Released on: {new Date(release.releaseDate).toLocaleDateString()}
            </div>
          </div>

          {release.whatsNew.map((feature, fIndex) => (
            <WhatsNewSection key={fIndex} feature={feature} />
          ))}
        </div>
      ))}
    </div>
  )
}

export default WhatsNewHistory
