import React from 'react'

import rawData from '@site/static/data/workflows.json'
import Heading from '@theme/Heading'
import cronstrue from 'cronstrue'

/** Metadata for a single GitHub Actions workflow, generated by fetchGHAWorkflowsData.js. */
interface WorkflowData {
  fileName: string
  name: string
  description: string | null
  usedBy: { name: string; fileName: string }[] | null
  uses: { name: string; fileName: string }[] | null
  on: Record<string, TriggerConfig> | string | string[]
  jobs: string[]
}

/** Configuration for a workflow trigger. Can also be an array for `schedule` triggers. */
interface TriggerConfig {
  branches?: string[] | string
  tags?: string[] | string
  types?: string[] | string
  paths?: string[] | string
  workflows?: string[]
  inputs?: Record<string, InputConfig>
  cron?: string
  [key: string]: any
}

interface InputConfig {
  description?: string
  type?: string
  default?: any
  required?: boolean
}

const data = rawData as WorkflowData[]

const GITHUB_WORKFLOW_BASE_URL =
  'https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/.github/workflows/'

const GITHUB_ACTION_BASE_URL = 'https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/'

// Maps raw GitHub Action trigger event names to human-friendly display labels
const friendlyTriggerNames: Record<string, string> = {
  create: 'Branch or Tag Created',
  issues: 'Issue',
  issue_comment: 'Issue Comment',
  pull_request_review: 'Pull Request Review',
  pull_request: 'Pull Request',
  push: 'Push',
  repository_dispatch: 'Called by other repos or external events (repository_dispatch)',
  schedule: 'Schedule',
  workflow_call: 'Used by other workflows (workflow_call):',
  workflow_dispatch: 'Manual Trigger (workflow_dispatch)',
  workflow_run: 'Triggered by other workflows (workflow_run)',
}

/** Converts snake_case or kebab-case to Title Case (e.g. "ready_for_review" → "Ready For Review"). */
const toTitleCase = (str: string): string =>
  str
    .split(/[-_]/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(' ')

/** Generates a URL-friendly slug from a workflow name or object (e.g. "[Build] Android" → "build-android"). */
export const getSlug = (item: string | { name: string; fileName?: string }): string => {
  const name = typeof item === 'string' ? item : item.name
  return name
    .toLowerCase()
    .replaceAll('[', '')
    .replaceAll(']', '')
    .replace(/\s+/g, '-')
    .replace(/[^\w-]/g, '')
}

/** Normalizes the `on` field to an object — handles YAML shorthand (string or array). */
const normalizeTriggers = (workflowOn: WorkflowData['on']): Record<string, TriggerConfig> => {
  if (typeof workflowOn === 'string') return { [workflowOn]: {} }
  if (Array.isArray(workflowOn)) return Object.fromEntries(workflowOn.map((t) => [t, {}]))
  return workflowOn || {}
}

/** Aggregates inputs from all triggers (primarily `workflow_call` and `workflow_dispatch`). */
const extractAllInputs = (on: Record<string, TriggerConfig>): Record<string, InputConfig> =>
  Object.values(on).reduce(
    (acc, config) => {
      if (config?.inputs) Object.assign(acc, config.inputs)
      return acc
    },
    {} as Record<string, InputConfig>,
  )

// Brief descriptions for each workflow group, shown in the table of contents
const groupDescriptions: Record<string, string> = {
  Admin: 'Team processes, repo admin, and maintenance tasks',
  Build: 'iOS and Android builds for QA and Release',
  'Code Quality': 'Linting, formatting, and static analysis',
  Documentation: 'Building and deploying documentation',
  E2E: 'End-to-end testing on iOS and Android',
  Release: 'App release process automation',
  Security: 'Security scanning and vulnerability detection',
  TestRail: 'Test case and result syncing with TestRail',
  Utils: 'Shared building blocks used by other workflows',
}

/** Grid-based table of contents for quick navigation between workflow groups. */
const TableOfContents: React.FC<{ groupedData: Record<string, WorkflowData[]> }> = ({ groupedData }) => {
  const sortedPrefixes = Object.keys(groupedData).sort()

  return (
    <div
      className="margin-bottom--xl p--md"
      style={{ background: 'var(--ifm-color-emphasis-100)', borderRadius: '8px', padding: '1.5rem' }}>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(250px, 1fr))', gap: '1.5rem' }}>
        {sortedPrefixes.map((prefix) => (
          <div key={prefix}>
            <h4 className="margin-bottom--sm" style={{ textTransform: 'capitalize' }}>
              {prefix}
            </h4>
            {groupDescriptions[prefix] && (
              <p className="margin-bottom--sm" style={{ fontSize: '0.8rem', color: 'var(--ifm-color-emphasis-700)' }}>
                {groupDescriptions[prefix]}
              </p>
            )}
            <ul style={{ listStyleType: 'none', paddingLeft: 0, fontSize: '0.9rem' }}>
              {groupedData[prefix].map((workflow) => (
                <li key={workflow.fileName} className="margin-bottom--xs">
                  <a href={`#${getSlug(workflow.name)}`}>
                    {/* Remove the bracketed prefix */}
                    {workflow.name.replace(/^\[.*?\]/, '').trim()}
                  </a>
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
    </div>
  )
}

/** Coerces a value that may be a single item or an array into an array. */
const toArray = <T,>(value: T | T[]): T[] => (Array.isArray(value) ? value : [value])

/** Renders filter details for a trigger (branches, tags, paths, cron schedules, etc.). */
const TriggerDetails: React.FC<{ trigger: string; triggerConfig: TriggerConfig | TriggerConfig[] }> = ({
  trigger,
  triggerConfig,
}) => {
  if (!triggerConfig || (typeof triggerConfig !== 'object' && !Array.isArray(triggerConfig))) return null

  const isSchedule = trigger === 'schedule'
  const isWorkflowRun = trigger === 'workflow_run'

  return (
    <ul className="text--small" style={{ listStyleType: 'none', paddingLeft: '1rem', marginTop: '0.25rem' }}>
      {isSchedule && Array.isArray(triggerConfig)
        ? triggerConfig.map((schedule: TriggerConfig, idx: number) => {
            let humanReadable = ''
            try {
              if (schedule.cron) {
                humanReadable = cronstrue.toString(schedule.cron)
              }
            } catch {
              humanReadable = 'Invalid cron expression'
            }
            return (
              <li key={idx}>
                Cron: <code>{schedule.cron}</code> ({humanReadable} UTC)
              </li>
            )
          })
        : typeof triggerConfig === 'object' &&
          !Array.isArray(triggerConfig) && (
            <>
              {isWorkflowRun && triggerConfig.workflows && (
                <li key="workflows">
                  Workflows:{' '}
                  {triggerConfig.workflows.map((parentName: string, i: number) => (
                    <React.Fragment key={parentName}>
                      {i > 0 && ', '}
                      <a href={`#${getSlug(parentName)}`}>{parentName}</a>
                    </React.Fragment>
                  ))}
                </li>
              )}

              {triggerConfig.branches && (
                <li key="branches">
                  Branches: <code>{toArray(triggerConfig.branches).join(', ')}</code>
                </li>
              )}

              {triggerConfig.tags && (
                <li key="tags">
                  Tags: <code>{toArray(triggerConfig.tags).join(', ')}</code>
                </li>
              )}

              {triggerConfig.types && (
                <li key="types">
                  When: <code>{toArray(triggerConfig.types).map(toTitleCase).join(', ')}</code>
                </li>
              )}

              {triggerConfig.paths && (
                <li key="paths">
                  File Paths:
                  <ul style={{ listStyleType: 'disc', paddingLeft: '1.5rem', marginTop: '0.25rem' }}>
                    {toArray(triggerConfig.paths).map((p: string) => (
                      <li key={p}>
                        <code>{p}</code>
                      </li>
                    ))}
                  </ul>
                </li>
              )}
            </>
          )}
    </ul>
  )
}

/** Renders a single trigger entry, including "Used By" links for reusable workflows. */
const WorkflowTrigger: React.FC<{
  trigger: string
  triggerConfig: TriggerConfig | TriggerConfig[]
  usedBy?: WorkflowData['usedBy']
}> = ({ trigger, triggerConfig, usedBy }) => {
  const baseName = friendlyTriggerNames[trigger] || trigger

  return (
    <li key={trigger} className="margin-bottom--sm">
      <strong>{baseName}</strong>
      <TriggerDetails trigger={trigger} triggerConfig={triggerConfig} />

      {/* For reusable workflows (workflow_call), display which workflows reference this one */}
      {trigger === 'workflow_call' && usedBy && (
        <ul className="margin-top--xs" style={{ listStyleType: 'circle', paddingLeft: '1.5rem' }}>
          {usedBy.map((caller) => (
            <li key={caller.fileName}>
              <a href={`#${getSlug(caller)}`}>{caller.name}</a>
            </li>
          ))}
        </ul>
      )}
    </li>
  )
}

/** Table of workflow input parameters (name, description, type, default, required). */
const InputsTable: React.FC<{ inputs: Record<string, InputConfig> }> = ({ inputs }) => {
  const entries = Object.entries(inputs)
  if (entries.length === 0) return null

  return (
    <div className="margin-bottom--md">
      <strong>Inputs:</strong>
      <div className="table-responsive margin-top--sm">
        <table>
          <thead>
            <tr>
              <th>Input</th>
              <th>Description</th>
              <th>Type</th>
              <th>Default</th>
              <th>Required</th>
            </tr>
          </thead>
          <tbody>
            {entries.map(([inputName, config]) => {
              const { description, type, default: defaultValue, required } = config
              const defaultDisplay =
                defaultValue !== undefined ? <code>{defaultValue === '' ? '""' : String(defaultValue)}</code> : '-'

              return (
                <tr key={inputName}>
                  <td>
                    <code>{inputName}</code>
                  </td>
                  <td>{description || '-'}</td>
                  <td>
                    <code>{type || 'string'}</code>
                  </td>
                  <td>{defaultDisplay}</td>
                  <td>{required ? 'Yes' : 'No'}</td>
                </tr>
              )
            })}
          </tbody>
        </table>
      </div>
    </div>
  )
}

/** Primary component — renders the full GHA workflow documentation page. */
const WorkflowsList: React.FC = () => {
  if (!data || data.length === 0) {
    return (
      <p>
        No workflow data available. Run <code>yarn prebuild</code> to generate it.
      </p>
    )
  }

  // Group workflows by their bracketed prefix (e.g. "[Build]", "[Release]")
  const groupedData = data.reduce(
    (acc, workflow) => {
      const match = workflow.name.match(/^\[(.*?)\]/)
      const prefix = match ? match[1] : 'Other'
      if (!acc[prefix]) acc[prefix] = []
      acc[prefix].push(workflow)
      return acc
    },
    {} as Record<string, WorkflowData[]>,
  )

  return (
    <div>
      <TableOfContents groupedData={groupedData} />
      <hr />

      {data.map((workflow) => {
        const slug = getSlug(workflow.name)
        const on = normalizeTriggers(workflow.on)
        const allInputs = extractAllInputs(on)

        return (
          <div key={workflow.fileName} className="margin-top--xl margin-bottom--xl">
            <Heading as="h2" id={slug} className="margin-bottom--sm">
              {workflow.name}
            </Heading>
            <p className="margin-bottom--sm" style={{ fontSize: '0.9rem', color: 'var(--ifm-color-emphasis-700)' }}>
              ({workflow.fileName})
            </p>
            {workflow.description && (
              <div>
                <p className="margin-bottom--sm">{workflow.description}</p>
              </div>
            )}

            <div className="margin-bottom--md" style={{ display: 'flex', gap: '0.5rem' }}>
              <a
                className="button button--outline button--sm button--secondary"
                href={`${GITHUB_WORKFLOW_BASE_URL}${workflow.fileName}`}
                target="_blank"
                rel="noopener noreferrer">
                Source
              </a>
              <a
                className="button button--outline button--sm button--secondary"
                href={`${GITHUB_ACTION_BASE_URL}${workflow.fileName}`}
                target="_blank"
                rel="noopener noreferrer">
                Runs
              </a>
            </div>

            <div className="margin-bottom--md">
              <strong>Triggers:</strong>
              <ul className="margin-top--sm">
                {Object.keys(on).map((trigger) => (
                  <WorkflowTrigger
                    key={trigger}
                    trigger={trigger}
                    triggerConfig={on[trigger]}
                    usedBy={workflow.usedBy}
                  />
                ))}
              </ul>
            </div>

            <InputsTable inputs={allInputs} />

            {workflow.uses && workflow.uses.length > 0 && (
              <div className="margin-bottom--md">
                <strong>Uses:</strong>
                <ul className="margin-top--xs" style={{ listStyleType: 'circle', paddingLeft: '1.5rem' }}>
                  {workflow.uses.map((ref) => (
                    <li key={ref.fileName}>
                      <a href={`#${getSlug(ref)}`}>{ref.name}</a>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            <div className="margin-top--lg text--right">
              <a href="#top" style={{ fontSize: '0.8rem' }}>
                ↑ Back to Top
              </a>
            </div>
            <hr className="margin-top--lg" />
          </div>
        )
      })}
    </div>
  )
}

export default WorkflowsList
