/**
 * WorkflowsList.tsx
 *
 * This component renders a comprehensive, interactive list of GitHub Actions
 * workflows used in the VA Mobile App repository. It consumes metadata
 * generated by the fetchGHAWorkflowsData.js script.
 */
import React from 'react'

import Link from '@docusaurus/Link'
import rawData from '@site/static/data/workflows.json'
import cronstrue from 'cronstrue'

// --- Types & Interfaces ---

/**
 * Metadata for a single GitHub Actions workflow.
 */
interface WorkflowData {
  fileName: string
  name: string
  description: string | null
  usedBy: string[] | null
  on: Record<string, TriggerConfig> | string | string[]
  jobs: string[]
}

/**
 * Configuration for a specific workflow trigger (e.g., push, schedule).
 * This can be an object with properties like branches, tags, types, paths, inputs,
 * or an array of schedule objects for 'schedule' triggers.
 */
interface TriggerConfig {
  branches?: string[] | string
  tags?: string[] | string
  types?: string[] | string
  paths?: string[] | string
  workflows?: string[]
  inputs?: Record<string, InputConfig>
  cron?: string // For schedule triggers
  [key: string]: any // Allow other arbitrary properties
}

/**
 * Configuration for a workflow input parameter.
 */
interface InputConfig {
  description?: string
  type?: string
  default?: any
  required?: boolean
}

// Cast the imported JSON to our typed interface for better IDE support and type safety.
const data = rawData as WorkflowData[]

// --- Constants ---

/**
 * Base URL for linking directly to the workflow source code on GitHub.
 */
const GITHUB_WORKFLOW_BASE_URL =
  'https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/.github/workflows/'

/**
 * Mapping of raw GitHub Action trigger event names to human-friendly display labels.
 */
const friendlyTriggerNames: Record<string, string> = {
  create: 'Branch or Tag Created',
  issues: 'Issue',
  issue_comment: 'Issue Comment',
  pull_request_review: 'Pull Request Review',
  pull_request: 'Pull Request',
  push: 'Push',
  repository_dispatch: 'Called by other repos or external events (repository_dispatch)',
  schedule: 'Schedule',
  workflow_call: 'Used by other workflows (workflow_call):',
  workflow_dispatch: 'Manual Trigger (workflow_dispatch)',
  workflow_run: 'Triggered by other workflows (workflow_run)',
}

// --- Utilities ---

/**
 * Converts snake_case or kebab-case strings to Title Case with spaces.
 * Useful for normalizing GitHub Action event types (e.g., "ready_for_review").
 *
 * @param str - The string to transform.
 * @returns The transformed string in Title Case.
 */
const toTitleCase = (str: string): string =>
  str
    .split(/[-_]/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(' ')

/**
 * Generates a URL-friendly slug from a workflow name or a workflow object.
 * This ensures that links (like #build-android) are consistent and predictable.
 *
 * @param item - The workflow name or a metadata object containing the name.
 * @returns A sanitized slug string.
 */
export const getSlug = (item: string | { name: string; fileName?: string }): string => {
  const name = typeof item === 'string' ? item : item.name
  return (
    name
      .toLowerCase()
      // Remove brackets used in prefixes like '[Build]'
      .replace(/\[|\]/g, '')
      // Replace spaces and special characters with hyphens
      .replace(/\s+/g, '-')
      .replace(/[^\w-]/g, '')
  )
}

/**
 * Normalizes the 'on' property of a workflow to ensure it's always an object.
 * Handles shorthand syntax where 'on' might be a string or an array of strings.
 *
 * @param workflowOn - The raw 'on' property from YAML.
 * @returns A normalized Record<string, TriggerConfig> of triggers.
 */
const normalizeTriggers = (workflowOn: WorkflowData['on']): Record<string, TriggerConfig> => {
  if (typeof workflowOn === 'string') return { [workflowOn]: {} }
  if (Array.isArray(workflowOn)) return workflowOn.reduce((acc, trigger) => ({ ...acc, [trigger]: {} }), {})
  return workflowOn || {}
}

/**
 * Aggregates all possible inputs from across all triggers in a workflow.
 * This is primarily used for 'workflow_call' and 'workflow_dispatch'.
 *
 * @param on - The normalized triggers object.
 * @returns A consolidated map of all inputs.
 */
const extractAllInputs = (on: Record<string, TriggerConfig>): Record<string, InputConfig> => {
  const allInputs: Record<string, InputConfig> = {}
  Object.keys(on).forEach((trigger) => {
    const triggerConfig = on[trigger]
    if (triggerConfig && triggerConfig.inputs) {
      Object.assign(allInputs, triggerConfig.inputs)
    }
  })
  return allInputs
}

// --- Internal View Components ---

/**
 * Renders a grid-based Table of Contents for quick navigation between workflow groups.
 */
const TableOfContents: React.FC<{ groupedData: Record<string, WorkflowData[]> }> = ({ groupedData }) => {
  const sortedPrefixes = Object.keys(groupedData).sort()

  return (
    <div
      className="margin-bottom--xl p--md"
      style={{ background: 'var(--ifm-color-emphasis-100)', borderRadius: '8px', padding: '1.5rem' }}>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(250px, 1fr))', gap: '1.5rem' }}>
        {sortedPrefixes.map((prefix) => (
          <div key={prefix}>
            <h4 className="margin-bottom--sm" style={{ textTransform: 'capitalize' }}>
              {prefix}
            </h4>
            <ul style={{ listStyleType: 'none', paddingLeft: 0, fontSize: '0.9rem' }}>
              {groupedData[prefix].map((workflow) => (
                <li key={workflow.fileName} className="margin-bottom--xs">
                  <Link to={`#${getSlug(workflow.name)}`}>
                    {/* Remove the bracketed prefix for a cleaner link list */}
                    {workflow.name.replace(/^\[.*?\]/, '').trim()}
                  </Link>
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
    </div>
  )
}

/**
 * Renders the filter details for a specific trigger (e.g., which branches, tags, or paths it applies to).
 */
const TriggerDetails: React.FC<{ trigger: string; triggerConfig: TriggerConfig | TriggerConfig[] }> = ({
  trigger,
  triggerConfig,
}) => {
  // Ensure triggerConfig is an object or array before proceeding
  if (!triggerConfig || (typeof triggerConfig !== 'object' && !Array.isArray(triggerConfig))) return null

  const isSchedule = trigger === 'schedule'
  const isWorkflowRun = trigger === 'workflow_run'

  return (
    <ul className="text--small" style={{ listStyleType: 'none', paddingLeft: '1rem', marginTop: '0.25rem' }}>
      {/* 1. Special handling for Cron Schedules */}
      {isSchedule && Array.isArray(triggerConfig)
        ? triggerConfig.map((schedule: TriggerConfig, idx: number) => {
            let humanReadable = ''
            try {
              if (schedule.cron) {
                humanReadable = cronstrue.toString(schedule.cron)
              }
            } catch {
              humanReadable = 'Invalid cron expression'
            }
            return (
              <li key={idx}>
                Cron: <code>{schedule.cron}</code> ({humanReadable} UTC)
              </li>
            )
          })
        : // For all other trigger types, triggerConfig is expected to be an object
          typeof triggerConfig === 'object' &&
          !Array.isArray(triggerConfig) && (
            <>
              {/* 2. Parent Workflow links for workflow_run triggers */}
              {isWorkflowRun && triggerConfig.workflows && (
                <li key="workflows">
                  Workflows:{' '}
                  {triggerConfig.workflows.map((parentName: string, i: number) => (
                    <React.Fragment key={parentName}>
                      {i > 0 && ', '}
                      <Link to={`#${getSlug(parentName)}`}>{parentName}</Link>
                    </React.Fragment>
                  ))}
                </li>
              )}

              {/* 3. Branch Filters */}
              {triggerConfig.branches && (
                <li key="branches">
                  Branches:{' '}
                  <code>
                    {(Array.isArray(triggerConfig.branches) ? triggerConfig.branches : [triggerConfig.branches]).join(
                      ', ',
                    )}
                  </code>
                </li>
              )}

              {/* 4. Tag Filters */}
              {triggerConfig.tags && (
                <li key="tags">
                  Tags:{' '}
                  <code>
                    {(Array.isArray(triggerConfig.tags) ? triggerConfig.tags : [triggerConfig.tags]).join(', ')}
                  </code>
                </li>
              )}

              {/* 5. Event subtype filters (opened, closed, etc.) */}
              {triggerConfig.types && (
                <li key="types">
                  When:{' '}
                  <code>
                    {(Array.isArray(triggerConfig.types) ? triggerConfig.types : [triggerConfig.types])
                      .map(toTitleCase)
                      .join(', ')}
                  </code>
                </li>
              )}

              {/* 6. File Path Filters */}
              {triggerConfig.paths &&
                (() => {
                  const paths = Array.isArray(triggerConfig.paths) ? triggerConfig.paths : [triggerConfig.paths]
                  return (
                    <li key="paths">
                      File Paths:
                      <ul style={{ listStyleType: 'disc', paddingLeft: '1.5rem', marginTop: '0.25rem' }}>
                        {paths.map((path: string) => (
                          <li key={path}>
                            <code>{path}</code>
                          </li>
                        ))}
                      </ul>
                    </li>
                  )
                })()}
            </>
          )}
    </ul>
  )
}

/**
 * Renders an individual trigger entry and handles the "Used By" relationships.
 */
const WorkflowTrigger: React.FC<{
  trigger: string
  triggerConfig: TriggerConfig | TriggerConfig[]
  usedBy?: string[] | null
}> = ({ trigger, triggerConfig, usedBy }) => {
  const baseName = friendlyTriggerNames[trigger] || trigger

  return (
    <li key={trigger} className="margin-bottom--sm">
      <strong>{baseName}</strong>
      <TriggerDetails trigger={trigger} triggerConfig={triggerConfig} />

      {/*
        For reusable workflows (workflow_call), we display which other
        workflows reference this one. This information is dynamically
        mapped by the backend script.
      */}
      {trigger === 'workflow_call' && usedBy && (
        <ul className="margin-top--xs" style={{ listStyleType: 'circle', paddingLeft: '1.5rem' }}>
          {usedBy.map((caller: string, i: number) => {
            // Internal links are built identifying the workflow name and filename
            // formatted as "Workflow Name (filename.yml)" in the JSON.
            const match = caller.match(/(.*) \((.*\.yml)\)/)
            if (match) {
              const [, name, fileName] = match
              return (
                <li key={i}>
                  <Link to={`#${getSlug({ name, fileName })}`}>{name}</Link>
                </li>
              )
            }
            return <li key={i}>{caller}</li>
          })}
        </ul>
      )}
    </li>
  )
}

/**
 * Renders a structured table detailing the workflow input parameters.
 */
const InputsTable: React.FC<{ inputs: Record<string, InputConfig> }> = ({ inputs }) => {
  const entries = Object.entries(inputs)
  if (entries.length === 0) return null

  return (
    <div className="margin-bottom--md">
      <strong>Inputs:</strong>
      <div className="table-responsive margin-top--sm">
        <table>
          <thead>
            <tr>
              <th>Input</th>
              <th>Description</th>
              <th>Type</th>
              <th>Default</th>
              <th>Required</th>
            </tr>
          </thead>
          <tbody>
            {entries.map(([inputName, config]) => {
              const { description, type, default: defaultValue, required } = config
              const defaultDisplay =
                defaultValue !== undefined ? <code>{defaultValue === '' ? '""' : String(defaultValue)}</code> : '-'

              return (
                <tr key={inputName}>
                  <td>
                    <code>{inputName}</code>
                  </td>
                  <td>{description || '-'}</td>
                  <td>
                    <code>{type || 'string'}</code>
                  </td>
                  <td>{defaultDisplay}</td>
                  <td>{required ? 'Yes' : 'No'}</td>
                </tr>
              )
            })}
          </tbody>
        </table>
      </div>
    </div>
  )
}

// --- Main Application Component ---

/**
 * The primary component that consumes workflow data and renders the documentation UI.
 */
const WorkflowsList: React.FC = () => {
  if (!data || data.length === 0) {
    return (
      <p>
        No workflow data available. Run <code>yarn prebuild</code> to generate it.
      </p>
    )
  }

  // Group workflows by their prefix (e.g., "[Build]", "[Release]") for better organization.
  const groupedData = data.reduce(
    (acc, workflow) => {
      const match = workflow.name.match(/^\[(.*?)\]/)
      const prefix = match ? match[1] : 'Other'
      if (!acc[prefix]) acc[prefix] = []
      acc[prefix].push(workflow)
      return acc
    },
    {} as Record<string, WorkflowData[]>,
  )

  return (
    <div>
      {/* 1. Quick Navigation Grid */}
      <TableOfContents groupedData={groupedData} />
      <hr />

      {/* 2. Detailed Workflow Entries */}
      {data.map((workflow) => {
        const slug = getSlug(workflow.name)
        const on = normalizeTriggers(workflow.on)
        const allInputs = extractAllInputs(on)

        return (
          <div key={workflow.fileName} id={slug} className="margin-top--xl margin-bottom--xl">
            <h2 className="margin-bottom--sm">{workflow.name}</h2>

            {/* Source Link */}
            <p className="margin-bottom--md">
              <strong>File:</strong>{' '}
              <a href={`${GITHUB_WORKFLOW_BASE_URL}${workflow.fileName}`} target="_blank" rel="noopener noreferrer">
                {workflow.fileName}
              </a>
            </p>

            {/* User-provided Description from comments */}
            {workflow.description && (
              <div className="margin-bottom--md">
                <p>{workflow.description}</p>
              </div>
            )}

            {/* Operational Triggers */}
            <div className="margin-bottom--md">
              <strong>Triggers:</strong>
              <ul className="margin-top--sm">
                {Object.keys(on).map((trigger) => (
                  <WorkflowTrigger
                    key={trigger}
                    trigger={trigger}
                    triggerConfig={on[trigger]}
                    usedBy={workflow.usedBy}
                  />
                ))}
              </ul>
            </div>

            {/* Optional inputs for manual/reusable triggers */}
            <InputsTable inputs={allInputs} />

            {/* Navigation Aid */}
            <div className="margin-top--lg text--right">
              <Link to="#top" style={{ fontSize: '0.8rem' }}>
                ↑ Back to Top
              </Link>
            </div>
            <hr className="margin-top--lg" />
          </div>
        )
      })}
    </div>
  )
}

export default WorkflowsList
