name: Automation Change Template
description: Template for requesting a change to the automation pipeline for the application
title: Automation - [Describe issue]
labels: devops
projects: ['department-of-veterans-affairs/1616']
assignees:
  - jbergman-oddball

body:
  - type: dropdown
    id: change-type
    attributes:
      label: Type of change
      description: What type of change are you completing
      options:
        - Update Existing Automation
        - Add new automation functionality
        - Fix Automation Bug
        - AWS Access
        - Github Migration

  - type: dropdown
    id: whats-changing
    attributes:
      label: What is chaging
      description: 'What systems/scripts are changing?'
      options:
        - Github Actions
        - Github Repo
        - AWS Infrastructure
        - Fastlane
        - Bash Scripts
        - Issue Templates
        - Other

  - type: input
    id: change-other
    attributes:
      label: If other, please specify
      description: 'Describe other change'

  - type: textarea
    id: work-done
    attributes:
      label: Work Being Done
      description: 'What is the work being done with this change?'

  - type: textarea
    id: testing-done
    attributes:
      label: Testing Done
      description: 'What testing did you do?'

  - type: textarea
    id: testing-reviewer
    attributes:
      label: Testing Reviewer
      description: 'What testing needs to be done by the reviewer?'

  - type: textarea
    id: testing-for-prod
    attributes:
      label: Testing for Prod
      description: 'What testing needs to be done to ensure this work is complete in production?'

  - type: textarea
    id: ac
    attributes:
      label: Acceptance Criteria
      description: 'What is the acceptance criteria?'
      placeholder: "- [ ] AC1\n- [ ] AC2"
