name: Automation Change Template
description: Template for requesting a change to the automation pipeline for the application
title: Automation - [Describe issue]
labels: devops
projects: ['department-of-veterans-affairs/1616']
assignees:
  - jbergman-oddball

body:
  - type: dropdown
    id: change-type
    attributes:
      label: change-type
      description: Type of Change
      options:
        - Update Existing Automation
        - Add new automation functionality
        - Fix Automation Bug
        - AWS Access
        - Github Migration

  - type: dropdown
    id: whats-changing
    attributes:
      label: change
      description: "What systems/scripts are changing?"
      options:
        - Github Actions
        - Github Repo
        - AWS Infrastructure
        - Fastlane
        - Bash Scripts
        - Issue Templates
        - Other

  - type: input
    id: change-other
    attributes:
      label: change-other
      description: "If change is not listed, please specify."

  - type: textarea
    id: work-done
    attributes:
      label: work-being-done
      description: "What is the work being done?"

  - type: textarea
    id: testing-done
    attributes:
      label: testing-done
      description: "What testing did you do?"

  - type: textarea
    id: testing-reviewer
    attributes:
      label: testing-reviewer
      description: "What testing needs to be done by the reviewer?"

  - type: textarea
    id: testing-for-prod
    attributes:
      label: testing-for-prod
      description: "What testing needs to be done to ensure this work is complete in production?"

  - type: textarea
    id: ac
    attributes:
      label: Acceptance Criteria
      description: "What is the acceptance criteria?"
      placeholder: "- [ ] AC1\n- [ ] AC2"
