name: VAHB Mobile App Change Request Form
description: Use this template to formally request a new feature, enhancement to a feature, discovery, research, analytics request or other ask/change for the VA Mobile App team to evaluate.
title: "Change Request: [name of change]"
labels: [ change-request ]
assignees: [ timwright12, Hallm13 ]
body:
- type: input
  id: fullname
  attributes:
    label: Requestor's Name
    description: Add your full name here
    placeholder: Example Name
  validations:
    required: true
- type: input
  id: email
  attributes:
    label: Requestor's Email
    description: Your email address so we can contact you with any follow-up questions.
    placeholder: 'example@va.gov'
  validations:
    required: true
- type: input
  id: VA_Team
  attributes:
    label: VA Team
    description: The VA Team you are with (Health Products, Benefit Tools Crew, CAIA, Identity, Contact Center, CAIA, etc) 
    placeholder: 
  validations:
    required: true    
- type: input
  id: change_request_label
  attributes:
    label: What is the name of the project or change? 
    description: Give us a short name or description for this feature, so we know what to call it.
  validations:
    required: true
- type: textarea
  id: description
  attributes:
    label: Please explain how this change would work.
    description: Giving us an explanation of how you feel this feature should work will help us better assess mobile implementation, planning and scoping. 
  validations:
    required: true
- type: textarea
  id: problem
  attributes:
    label: Please explain what problem you are trying to solve.  
    description: Giving us an explanation what the current problem is and what the current Veteran experience is will help us better assess mobile implementation, planning and scoping. 
  validations:
    required: true
- type: input
  id: Feature
  attributes:
    label: Features Impacted
    description: What features will this change involve (Appointments, Prescriptions, Secure Messaging, Direct Deposit, Payments, Vaccines, Contact Information, etc.)
    placeholder: If this is a new feature request put NA. 
  validations:
    required: true  
- type: textarea
  id: existing_documentation
  attributes:
    label: Please include all existing relevant documentation links for this change request?  
    description: Giving us access to documentation (product brief, APIs, research, web experience, flows, Github folder, etc) will allow Mobile to further research and review existing materials.  
  validations:
    required: true
- type: textarea
  id: mobile_readiness
  attributes:
    label: Does your team have all the necessary materials (documents, designs, processes, analytics, APIs, etc) in place for Mobile to make these changes right now? 
    description: Mobile wants to understand if the necessary integrations and project pre-requesistes are completed now or if Mobile will be blocked until future work is completed in order to better asses planning, scoping, and prioritization. 
  validations:
    required: true
- type: input
  id: discussion_VAHB_PO
  attributes:
    label: Has this change been discussed with VAHB POs (Rachel, Ryan, or Don)? 
    description: Have you talked to any of the Mobile VA POs regarding this change? 
    placeholder: VAHB PO Name  - Yes / No
  validations:
    required: true
- type: input
  id: duedate
  attributes:
    label: What is your ideal due date for this change request? 
    description: Understanding requested due date will help us better assess planning, scoping, and prioritization. 
    placeholder: MM/DD/YYYY or Quarter 
  validations:
    required: true    

