name: VAHB Mobile App Change Request Form
description: Use this template to formally request a new feature, enhancement to a feature, discovery, research, analytics request or other ask/change for the VA Mobile App team to evaluate.
title: "Change Request: [name of change]"
labels: [ "Change Request", "Leads team", "needs-review" ]
projects: ["department-of-veterans-affairs/1616"]
assignees: 
  - rtwell
  - beccatupaj
body:
- type: input
  id: requestor_name_and_email
  attributes:
    label: 1.) Requestor's Name and Email
    description: Add your full name and email here so we can contact you with any follow-up questions
    placeholder: Example Name and Email
  validations:
    required: true
- type: input
  id: PO_name_and_email
  attributes:
    label: 2.) PO's Name and Email
    description: PO's name and email address so we can contact with questions related to feature approval.
    placeholder: Example Name and Email
  validations:
    required: true
- type: input
  id: VA_Team
  attributes:
    label: 3.) VA Team
    description: The VA Team you are with (Health Products, Benefit Tools Crew, Identity, Contact Center, CAIA, etc) 
    placeholder: 
  validations:
    required: true    
- type: input
  id: change_request_label
  attributes:
    label: 4.) What is the name of the project or change? 
    description: Give us a short name or description for this feature, so we know what to call it.
  validations:
    required: true
- type: textarea
  id: problem
  attributes:
    label: 5.) Please explain what problem you are trying to solve.  
    description: Describe the problem and its impact on Veteran experience so we can assess mobile implementation. 
  validations:
    required: true
- type: textarea
  id: description
  attributes:
    label: 6.) Please explain how this change would work.
    description: Please explain how this change or feature would solve the problem. 
  validations:
    required: true
- type: input
  id: Feature
  attributes:
    label: 7.) Features Impacted
    description: What features will this change involve (Appointments, Prescriptions, Secure Messaging, Direct Deposit, Payments, Vaccines, Contact Information, etc.)
    placeholder: If this is a new feature request put NA. 
  validations:
    required: true  
- type: textarea
  id: existing_documentation
  attributes:
    label: 8.) Does your team have all the necessary materials (documents, designs, processes, analytics, APIs, etc) in place for Mobile to make these changes right now? Please include all relevant documentation links.  
    description: Giving us access to documentation (product brief, APIs, research, web experience, flows, Github folder, etc) will allow the Mobile App Team to review and accurately assess this request. Missing information could result in your request being blocked or delayed.  
  validations:
    required: true
- type: input
  id: mobile_readiness
  attributes:
    label: 9.) Does this request require backend work? If so, has the backend work for this been completed, or will backend support be needed from Mobile team?  
    description: Mobile wants to understand how to assess the effort needed to implement this request. 
    placeholder: Yes / No
  validations:
    required: true
- type: input
  id: discussion_VAHB_PO
  attributes:
    label: 10.) Has this change been discussed with VAHB POs (Ryan or Don)? 
    description: 
    placeholder: VAHB PO Name  - Yes / No
  validations:
    required: true
- type: input
  id: va_stakedholer_alignment
  attributes:
    label: 11.) Has this change been agreed upon by all impacted VA Stakeholders? 
    description: 
    placeholder: Yes / No
  validations:
    required: true
- type: input
  id: duedate
  attributes:
    label: 12.) Is there a hard deadline associated with this request? If so, can you please explain why this deadline is selected and potential impacts to the app or other services if this deadline is not met?
    description: 
    placeholder: MM/DD/YYYY 
  validations:
    required: true    

