name: Onboarding Request (Engineering)
description: Fill out this form to request initiation of engineering onboarding for 
title: "Onboarding: [name]"
labels: [ onboarding ]
assignees: timwright12
body:
- type: markdown
  attributes:
    value: |
      **Please read before continuing**: This issue form is to request to start the onboarding process for an engineer planning to work in the VA Mobile App.
      After this issue is reviewed it will be dual-assigned to an onboarding point of contact and the team member who is being onboarded for completion.

- type: input
  id: fullname
  attributes:
    label: Full Name
    description: Users Full Name
    placeholder: Alex Smith
  validations:
    required: true
- type: input
  id: username
  attributes:
    label: GitHub Username
    description: Before mobile onboarding this user must already be within the VA Github Organization
    placeholder: '@Alex-smith-va'
  validations:
    required: true

- type: input
  id: vaemail
  attributes:
    label: VA Email Address
    description: Onboarding requires a VA email address to access developer systems
    placeholder: 'Alex.Smith1@va.gov'
  validations:
    required: true

- type: input
  id: teamname
  attributes:
    label: Which team is this person on?
    description: Exposing the primary team name helps us sort access requests
  validations:
    required: true

- type: input
  id: vaoctopo
  attributes:
    label: Who is the OCTO Product Owner for this person's team? 
    description: Add a PO helps us triage requests, and know who the main point of contact is.
  validations:
    required: true

- type: input
  id: slackchannel
  attributes:
    label: What is the main Slack channel for this person's team primary team?
    description: Slack channels help when we need to contact the rest of the team or easily check in.
    placeholder: '#va-mobile-app'
  validations:
    required: true

- type: markdown
  attributes:
    value: |
      The checklist items below should be left blank, as they will be filled out during the onboarding process.

- type: checkboxes
  attributes:
    label: Process Documentation
    description: As you've started onboarding, please check off the documentation as you read through it. All documentation should be reviewed, but we've called out some specifics below to help guide onboarding.
    options:
    - label: Read and bookmark [VA mobile general documentation](https://department-of-veterans-affairs.github.io/va-mobile-app/)
    - label: Read about [how push notifications work in the app](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/BackEnd/Features/PushNotifications)
    - label: Review [accessibility information](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/FrontEnd/AccessibilityInformation)
    - label: Read about [how the QA team works with others](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA/QualityAssuranceProcess/working-with-others)
    - label: Review the [release overview](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/Teams/QA%20and%20Release/Release%20Management)
    - label: Review the [release policies](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/Teams/QA%20and%20Release/Policies)
   

- type: checkboxes
  attributes:
    label: System Access
    description: Before system access can be granted, the user _must_ be onboarded into VA Github Organization
    options:
    - label: App store connect (VA Mobile will provide)
    - label: Firebase (VA Mobile will provide)
    - label: Write access to applicable repositories (VA Mobile will provide)
    - label: Join [#va-mobile-app slack channel](https://dsva.slack.com/archives/C018V2JCWRJ)

- type: checkboxes
  attributes:
    label: Engineering-specific documentation
    description: After access has been granted, start getting the app set up locally and reviewing important implementation documentation
    options:
    - label: Familiarize yourself with the [va-mobile-app repository](https://github.com/department-of-veterans-affairs/va-mobile-app)
    - label: Review [mobile API documentation](https://department-of-veterans-affairs.github.io/va-mobile-app/api/)
    - label: Get a high level understanding about [how authentication works in the app](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/BackEnd/Architecture/Auth%20Diagrams)
    - label: Read [remote configuration documentation](https://firebase.google.com/docs/remote-config/)
    - label: Get up to speed on the [Mobile Design System](https://department-of-veterans-affairs.github.io/va-mobile-app/design/Intro)
    - label: Review [how to set up deep linking in th app](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/FrontEnd/PushNotifications/DeepLinking)
    - label: Review [development best practices](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/FrontEnd/DevelopmentBestPractices)
    - label: Review [information about unit tests](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/FrontEnd/Testing/UnitTesting)
    - label: Review [information about end-to-end testing with Detox](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA/QualityAssuranceProcess/Automation/)
    - label: Review [best practice documentation around end-to-end testing](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA/QualityAssuranceProcess/Automation/Detox%20Best%20Practices)
    - label: Review [technical details around the mobile release process](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Operations/Releases/release-process)
    - label: Start [getting the app setup locally](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/FrontEnd/DevSetupProcess)
    - label: Information about [accessing Demo Mode](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/Mobile%20Demo%20Mode)
