export const API_ROOT = 'https://test-api'
export const AUTH_REDIRECT_URL = 'vamobile://login-success'
export const AUTH_SCOPES = 'openid'
export const AUTH_SIS_ENDPOINT = 'https://test.gov/sign_in'
export const AUTH_SIS_TOKEN_EXCHANGE_URL = 'https://test.gov/sign_in/token'
export const AUTH_SIS_REFRESH_URL = 'https://test.gov/sign_in/refresh'
export const AUTH_SIS_REVOKE_URL = 'https://test.gov/sign_in/revoke'
export const SHOW_DEBUG_MENU = true
export const IS_TEST = true
export const WEBVIEW_URL_CHANGE_LEGAL_NAME =
  'https://www.va.gov/resources/how-to-change-your-legal-name-on-file-with-va/'
export const WEBVIEW_URL_CORONA_FAQ = 'https://www.va.gov/coronavirus-veteran-frequently-asked-questions'
export const WEBVIEW_URL_FACILITY_LOCATOR = 'https://www.va.gov/find-locations/'
export const LINK_URL_MHV_VA_MEDICAL_RECORDS = 'https://www.va.gov/my-health/medical-records/'
export const LINK_URL_VA_NOTIFICATIONS = 'https://www.va.gov/profile/notifications/'
export const LINK_URL_VA_SCHEDULING = 'https://www.va.gov/health-care/schedule-view-va-appointments/'
export const LINK_URL_IN_APP_RECRUITMENT =
  'https://docs.google.com/forms/d/e/1FAIpQLSfRb0OtW34qKm8tGoQwwwDFs8IqwOMCLTde3DeM-ukKOEZBnA/viewform'
export const LINK_URL_VETERAN_USABILITY_PROJECT = 'https://veteranusability.us/'
export const LINK_URL_VETERANS_CRISIS_LINE = 'https://www.veteranscrisisline.net/'
export const LINK_URL_VETERANS_CRISIS_LINE_GET_HELP = 'https://www.veteranscrisisline.net/get-help/chat'
export const LINK_URL_SCHEDULE_APPOINTMENTS = 'https://www.va.gov/health-care/schedule-view-va-appointments/'
export const LINK_URL_PRIVACY_POLICY = 'https://www.va.gov/privacy-policy/'
export const LINK_URL_DECISION_REVIEWS = 'https://www.va.gov/decision-reviews/'
export const LINK_URL_COMPENSATION_CLAIM_EXAM = 'https://benefits.va.gov/compensation/claimexam.asp'
export const LINK_URL_YOUR_CLAIMS = 'https://www.va.gov/your-claims'
export const LINK_URL_CLAIM_APPEAL_STATUS = 'https://www.va.gov/claim-or-appeal-status/'
export const LINK_URL_UPGRADE_MY_HEALTHEVET_PREMIUM_ACCOUNT =
  'https://www.myhealth.va.gov/web/myhealthevet/upgrading-your-my-healthevet-account-through-in-person-or-online-authentication'
export const LINK_URL_GO_TO_MY_HEALTHEVET =
  'https://www.myhealth.va.gov/mhv-portal-web/user-login?redirect=/mhv-portal-web/web/myhealthevet/secure-messaging'
export const LINK_URL_OMB_PAGE = 'https://www.reginfo.gov/public/do/PRAMain'
export const APPLE_STORE_LINK = 'https://apps.apple.com/us/app/va-health-and-benefits/id1559609596'
export const GOOGLE_PLAY_LINK = 'https://play.google.com/store/apps/details?id=gov.va.mobileapp'
export const LINK_URL_GO_TO_PATIENT_PORTAL = 'https://patientportal.myhealth.va.gov/'
export const LINK_URL_ASK_VA_GOV = 'https://ask.va.gov/'
export const LINK_URL_GO_TO_VA_GOV = 'https://va.gov'
export const LINK_URL_ABOUT_PACT_ACT = 'https://www.va.gov/resources/the-pact-act-and-your-va-benefits/'
export const LINK_URL_APPLY_FOR_HEALTH_CARE = 'https://www.va.gov/health-care/apply/application/introduction'
export const LINK_URL_VA_FORM_10_3542 = 'https://www.va.gov/resources/va-form-10-3542/'
export const LINK_URL_TRAVEL_PAY_FILE_CLAIM_BTSSS =
  'https://www.va.gov/health-care/get-reimbursed-for-travel-pay/#file-a-claim-for-general-health'
export const LINK_URL_TRAVEL_PAY_ELIGIBILITY =
  'https://www.va.gov/health-care/get-reimbursed-for-travel-pay/#eligibility-for-general-health'
export const LINK_URL_TRAVEL_PAY_SET_UP_DIRECT_DEPOSIT =
  'https://www.va.gov/resources/how-to-set-up-direct-deposit-for-va-travel-pay-reimbursement/'
export const ENVIRONMENT = 'test'
export const CARRIER_TRACKING_URL_USPS = 'https://tools.usps.com/go/TrackConfirmAction_input?strOrigTrackNum='
export const CARRIER_TRACKING_URL_UPS = 'https://wwwapps.ups.com/WebTracking/track?track=yes&trackNums='
export const CARRIER_TRACKING_URL_FEDEX = 'https://www.fedex.com/apps/fedextrack/?tracknumbers='
export const CARRIER_TRACKING_URL_DHL = 'https://www.dhl.com/en/express/tracking.html?AWB='
export const DEMO_PASSWORD = 'Zhuzh-it'
