export { default as AppointmentsScreen } from './AppointmentsScreen/AppointmentsScreen'
export { default as ClaimsScreen } from './ClaimsScreen/ClaimsScreen'
export { default as HomeScreen } from './HomeScreen/HomeScreen'
export { default as ProfileScreen } from './ProfileScreen/ProfileScreen'
export { default as LoginScreen } from './LoginScreen/LoginScreen'
