export { default as HealthScreen } from './HealthScreen'
export { getHealthScreens } from './HealthScreen'
export { default as ClaimsScreen } from './ClaimsScreen'
export { getClaimsScreens } from './ClaimsScreen'
export { default as HomeScreen } from './HomeScreen'
export { getHomeScreens } from './HomeScreen'
export { default as ProfileScreen } from './ProfileScreen'
export { getProfileScreens } from './ProfileScreen'
export { default as PaymentsScreen } from './PaymentsScreen'
export { getPaymentsScreens } from './PaymentsScreen'
export { default as LoginScreen } from './auth/LoginScreen'

