# Native configuration for actionlint

ignore:
  - "[shellcheck]"
  - "action is too old to run"

disable:
  - action # Disables the check for outdated actions like checkout@v3
  - shellcheck # Disables all shellcheck warnings
  - syntax-check
