export * from './createPhoneNumber'
export * from './deletePhoneNumber'
export * from './deleteEmail'
export * from './getContactInformation'
export * from './updateAddress'
export * from './updateEmail'
export * from './updatePhoneNumber'
export * from './validateAddress'
