version: '3.1'

services:

  app:
    build:
      context: ./
      dockerfile: docker/dev.Dockerfile
    stdin_open: true
    ports:
      - 8081:8081
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
