const fullTestRun = [
  'Allergies',
  'LabsAndTests',
  'Appeals',
  'AppealsExpanded',
  'Appointments',
  'AppointmentsExpanded',
  'AppointmentsTestTime',
  'AvailabilityFramework',
  'Cerner',
  'Claims',
  'ContactInformation',
  'DecisionLetters',
  'DirectDeposit',
  'DisabilityRatings',
  'HomeScreen',
  'LoginScreen',
  'Messages',
  'MilitaryInformation',
  'Navigation',
  'Onboarding',
  'Payments',
  'PersonalInformationScreen',
  'Prescriptions',
  'ProfileScreen',
  'SettingsScreen',
  'VaccineRecords',
  'VALetters',
  'VeteransCrisisLine',
  'VeteranStatusCard',
] as const

export const detoxMapping = {
  directory: {
    allergies: ['Allergies'],
    appointments: ['Appointments', 'AppointmentsExpanded', 'TravelPay'],
    authorizedServices: [
      'Appeals',
      'AppealsExpanded',
      'Appointments',
      'AppointmentsExpanded',
      'AppointmentsTestTime',
      'Claims',
      'DirectDeposit',
      'DisabilityRatings',
      'PersonalInformationScreen',
      'VALetters',
      'MilitaryInformation',
      'Payments',
      'Prescriptions',
      'Messages',
      'VeteranStatusCard',
    ],
    claimsAndAppeals: ['Appeals', 'AppealsExpanded', 'Claims'],
    contactInformation: ['ContactInformation', 'VALetters'],
    decisionLetters: ['DecisionLetters'],
    demographics: ['PersonalInformationScreen', 'VeteranStatusCard', 'HomeScreen', 'ProfileScreen'],
    directDeposit: ['DirectDeposit'],
    disabilityRating: ['DisabilityRatings', 'VeteranStatusCard'],
    facilities: ['Cerner'],
    labsAndTests: ['LabsAndTests'],
    letters: ['VALetters'],
    militaryService: ['MilitaryInformation', 'VeteranStatusCard'],
    notifications: ['SettingsScreen', 'PushNotifications'],
    payments: ['Payments'],
    personalInformation: ['PersonalInformationScreen', 'VeteranStatusCard', 'HomeScreen', 'ProfileScreen'],
    prescriptions: ['Prescriptions'],
    secureMessaging: ['Messages'],
    types: [...fullTestRun],
    vaccines: ['VaccineRecords'],
    components: [...fullTestRun],
    LoginScreen: ['LoginScreen'],
    AppealDetailsScreen: ['Appeals', 'AppealsExpanded'],
    ClaimDetailsScreen: ['Claims'],
    ClaimLettersScreen: ['Claims'],
    ClaimsAndAppealsListView: ['Appeals', 'AppealsExpanded', 'Claims'],
    ClaimsHistoryScreen: ['Claims'],
    NeedHelpData: ['Appeals', 'AppealsExpanded', 'Claims'],
    NoClaimsAndAppeals: ['Appeals', 'AppealsExpanded', 'Claims'],
    NoClaimsAndAppealsAccess: ['Appeals', 'AppealsExpanded', 'Claims'],
    ClaimsScreen: ['Appeals', 'AppealsExpanded', 'Claims'],
    DisabilityRatingsScreen: ['DisabilityRatings', 'VeteranStatusCard'],
    Letters: ['VALetters'],
    Appointments: ['Appointments', 'AppointmentsExpanded', 'AppointmentsTestTime'],
    CernerAlert: ['Cerner'],
    HealthHelp: ['Cerner'],
    Pharmacy: ['Prescriptions'],
    SecureMessaging: ['Messages'],
    Vaccines: ['VaccineRecords'],
    ContactVAScreen: ['HomeScreen'],
    ProfileScreen: [
      'ProfileScreen',
      'ContactInformation',
      'MilitaryInformation',
      'PersonalInformationScreen',
      'SettingsScreen',
      'VALetters',
      'Payments',
    ],
    ContactInformationScreen: ['ContactInformation', 'VALetters'],
    MilitaryInformationScreen: ['MilitaryInformation', 'VeteranStatusCard'],
    PersonalInformationScreen: ['PersonalInformationScreen', 'VeteranStatusCard', 'HomeScreen', 'ProfileScreen'],
    VeteransCrisisLineScreen: ['VeteransCrisisLine', 'SignIn'],
    VeteranStatusScreen: ['VeteranStatusCard'],
    OnboardingCarousel: ['Onboarding'],
    RequestNotifications: ['Onboarding'],
    DirectDepositScreen: ['DirectDeposit'],
    PaymentHistory: ['Payments'],
    SplashScreen: ['Onboarding', 'LoginScreen'],
    BenefitsScreen: ['DisabilityRatings', 'Claims', 'Appeals', 'VALetters'],
    HealthScreen: [
      'Appointments',
      'AppointmentsExpanded',
      'AppointmentsTestTime',
      'Cerner',
      'Prescriptions',
      'Messages',
      'VaccineRecords',
    ],
    HomeScreen: ['HomeScreen', 'ProfileScreen', 'VeteranStatusCard'],
    SettingsScreen: ['SettingsScreen'],
    PaymentsScreen: ['Payments', 'DirectDeposit'],
    slices: [...fullTestRun],
    translations: [...fullTestRun],
    travelPay: ['TravelPay'],
    utils: [...fullTestRun],
    device: [],
    BiometricsPreferenceScreen: [],
    SyncScreen: [],
    WebviewScreen: [],
    styles: [],
    TravelPay: ['TravelPay'],
    benjaminAdams: [],
    claraJefferson: [],
    kimberlyWashington: [],
    dennisMadison: [],
  },
  files: {
    'allergies.ts': ['Allergies'],
    'labsAndTests.ts': ['LabsAndTests'],
    'accounts.ts': ['DirectDeposit'],
    'appointments.ts': ['Appointments', 'AppointmentsExpanded', 'TravelPay', 'AppointmentsTestTime'],
    'claims.ts': ['Claims', 'Appeals', 'AppealsExpanded'],
    'common.ts': [...fullTestRun],
    'countries.ts': ['ContactInformation'],
    'gmtTimezones.ts': ['Appointments', 'AppointmentsExpanded', 'AppointmentsTestTime'],
    'militaryPostOffices.ts': ['ContactInformation'],
    'militaryStates.ts': ['ContactInformation'],
    'screens.ts': [...fullTestRun],
    'secureMessaging.ts': ['Messages'],
    'states.ts': ['ContactInformation'],
    'appointmentsTestTime.json': ['AppointmentsTestTime'],
    'appointments.json': ['Appointments', 'AppointmentsExpanded'],
    'claims.json': ['Claims', 'Appeals', 'AppealsExpanded'],
    'contactInformation.json': ['ContactInformation', 'VALetters'],
    'decisionLetters.json': ['DecisionLetters'],
    'disabilityRating.json': ['DisabilityRatings'],
    'getAuthorizedServices.json': [
      'Appeals',
      'AppealsExpanded',
      'Appointments',
      'AppointmentsExpanded',
      'AppointmentsTestTime',
      'Claims',
      'DirectDeposit',
      'DisabilityRatings',
      'PersonalInformationScreen',
      'VALetters',
      'MilitaryInformation',
      'Payments',
      'Prescriptions',
      'Messages',
      'VeteranStatusCard',
    ],
    'getFacilitiesInfo.json': ['Cerner'],
    'getFacilitiesInfoCerner.json': ['Cerner'],
    'letters.json': ['VALetters'],
    'notifications.json': ['SettingsScreen', 'PushNotifications'],
    'payments.json': ['Payments'],
    'personalInformation.json': ['PersonalInformationScreen', 'VeteranStatusCard', 'HomeScreen', 'ProfileScreen'],
    'prescriptions.json': ['Prescriptions'],
    'profile.json': [
      'ProfileScreen',
      'ContactInformation',
      'MilitaryInformation',
      'PersonalInformationScreen',
      'SettingsScreen',
      'VALetters',
      'Payments',
    ],
    'secureMessaging.json': ['Messages'],
    'vaccine.json': ['VaccineRecords'],
    'decisionLetters.ts': ['DecisionLetters'],
    'demographics.ts': ['PersonalInformationScreen', 'VeteranStatusCard', 'HomeScreen', 'ProfileScreen'],
    'disabilityRating.ts': ['DisabilityRatings'],
    'letters.ts': ['VALetters'],
    'notifications.ts': ['SettingsScreen', 'PushNotifications'],
    'payments.ts': ['Payments'],
    'profile.ts': [
      'ProfileScreen',
      'ContactInformation',
      'MilitaryInformation',
      'PersonalInformationScreen',
      'SettingsScreen',
      'VALetters',
      'Payments',
    ],
    'travelPay.ts': ['TravelPay'],
    'vaccine.ts': ['VaccineRecords'],
    'api.ts': [...fullTestRun],
    'App.tsx': [...fullTestRun],
    'App.test.tsx': [],
    'analytics.ts': [],
    'backButtonLabels.ts': [],
    'documentTypes.ts': [],
    'errors.ts': [],
    'linking.tsx': [],
    'namespaces.ts': [],
    'store.ts': [],
    'utils.ts': [],
    'allergies.json': ['Allergies'],
    'labsAndTests.json': ['LabsAndTests'],
    'users.ts': [],
  },
} as const

// Export the full test run array separately if needed
export { fullTestRun }

// Default export
export default detoxMapping
