// Reusable array variables for detox mapping

// Full test run - used by components, slices, translations, utils
const fullTestRun = [
  'Allergies',
  'AllergiesAccelerated',
  'Appeals',
  'AppealsExpanded',
  'Appointments',
  'AppointmentsExpanded',
  'AppointmentsTestTime',
  'AvailabilityFramework',
  'Cerner',
  'Claims',
  'ContactInformation',
  'DecisionLetters',
  'DirectDeposit',
  'DisabilityRatings',
  'HomeScreen',
  'LabsAndTests',
  'LoginScreen',
  'Messages',
  'MilitaryInformation',
  'Navigation',
  'Onboarding',
  'Payments',
  'PersonalInformationScreen',
  'Prescriptions',
  'ProfileScreen',
  'PushNotifications',
  'SettingsScreen',
  'SignIn',
  'TravelPay',
  'TravelPayClaims',
  'VaccineRecords',
  'VALetters',
  'VeteransCrisisLine',
  'VeteranStatusCard',
]

// Authorized services array
const authorizedServicesArray = [
  'Appeals',
  'AppealsExpanded',
  'Appointments',
  'AppointmentsExpanded',
  'AppointmentsTestTime',
  'Claims',
  'DirectDeposit',
  'DisabilityRatings',
  'PersonalInformationScreen',
  'VALetters',
  'MilitaryInformation',
  'Payments',
  'Prescriptions',
  'Messages',
  'VeteranStatusCard',
]

const healthScreenArray = [
  'Appointments',
  'AppointmentsExpanded',
  'AppointmentsTestTime',
  'Cerner',
  'Messages',
  'Prescriptions',
  'TravelPay',
  'VaccineRecords',
]
const homeScreenArray = ['HomeScreen', 'ProfileScreen', 'VeteranStatusCard']
const benefitsScreenArray = ['DisabilityRatings', 'Claims', 'Appeals', 'VALetters']
const profileScreenArray = [
  'ProfileScreen',
  'ContactInformation',
  'MilitaryInformation',
  'PersonalInformationScreen',
  'SettingsScreen',
  'VALetters',
  'Payments',
]

const claimsAndAppealsArray = ['Appeals', 'AppealsExpanded', 'Claims']
const contactInfoArray = ['ContactInformation', 'VALetters']
const demographicsArray = ['PersonalInformationScreen', 'VeteranStatusCard', 'HomeScreen', 'ProfileScreen']
const disabilityVeteranArray = ['DisabilityRatings', 'VeteranStatusCard']
const appointmentsArray = ['Appointments', 'AppointmentsExpanded', 'AppointmentsTestTime', 'TravelPay']
const notificationsArray = ['SettingsScreen', 'PushNotifications']
// TODO: The rest of the Overpay/Copay screens still need to be added to project
const medicalCopaysArray = ['Payments']
const debtsArray = ['Payments']

const detoxMapping = {
  directory: {
    allergies: ['Allergies', 'AllergiesAccelerated'],
    AppealDetailsScreen: ['Appeals', 'AppealsExpanded'],
    Appointments: appointmentsArray,
    authorizedServices: authorizedServicesArray,
    BenefitsScreen: benefitsScreenArray,
    benjaminAdams: [],
    BiometricsPreferenceScreen: [],
    claimsAndAppeals: claimsAndAppealsArray,
    ClaimDetailsScreen: ['Claims'],
    ClaimLettersScreen: ['Claims'],
    ClaimsAndAppealsListView: claimsAndAppealsArray,
    ClaimsHistoryScreen: ['Claims'],
    ClaimsScreen: [...claimsAndAppealsArray, 'TravelPay'],
    claraJefferson: [],
    components: fullTestRun,
    contactInformation: contactInfoArray,
    ContactInformationScreen: contactInfoArray,
    ContactVAScreen: ['HomeScreen'],
    decisionLetters: ['DecisionLetters'],
    demographics: demographicsArray,
    dennisMadison: [],
    device: [],
    directDeposit: ['DirectDeposit'],
    DirectDepositScreen: ['DirectDeposit'],
    disabilityRating: disabilityVeteranArray,
    DisabilityRatingsScreen: disabilityVeteranArray,
    facilities: ['Cerner'],
    HealthScreen: healthScreenArray,
    HomeScreen: homeScreenArray,
    kimberlyWashington: [],
    labsAndTests: ['LabsAndTests'],
    Letters: ['VALetters'],
    letters: ['VALetters'],
    LoginScreen: ['LoginScreen'],
    maintenanceWindows: fullTestRun,
    militaryService: ['MilitaryInformation', 'VeteranStatusCard'],
    MilitaryInformationScreen: ['MilitaryInformation', 'VeteranStatusCard'],
    NeedHelpData: claimsAndAppealsArray,
    NoClaimsAndAppeals: claimsAndAppealsArray,
    NoClaimsAndAppealsAccess: claimsAndAppealsArray,
    notifications: notificationsArray,
    OnboardingCarousel: ['Onboarding'],
    payments: ['Payments'],
    PaymentHistory: ['Payments'],
    PaymentsScreen: ['Payments', 'DirectDeposit'],
    personalInformation: demographicsArray,
    PersonalInformationScreen: demographicsArray,
    Pharmacy: ['Prescriptions'],
    prescriptions: ['Prescriptions'],
    ProfileScreen: profileScreenArray,
    RequestNotifications: ['Onboarding'],
    secureMessaging: ['Messages'],
    SecureMessaging: ['Messages'],
    SettingsScreen: ['SettingsScreen'],
    slices: fullTestRun,
    SplashScreen: ['Onboarding', 'LoginScreen'],
    store: fullTestRun,
    styles: [],
    SyncScreen: [],
    translations: fullTestRun,
    travelPay: ['TravelPay', 'TravelPayClaims'],
    TravelPay: ['TravelPay', 'TravelPayClaims'],
    types: fullTestRun,
    utils: fullTestRun,
    vaccines: ['VaccineRecords'],
    Vaccines: ['VaccineRecords'],
    VeteransCrisisLineScreen: ['VeteransCrisisLine', 'SignIn'],
    VeteranStatusScreen: ['VeteranStatusCard'],
    WebviewScreen: [],
  },
  files: {
    'accounts.ts': ['DirectDeposit'],
    'allergies.json': ['Allergies', 'AllergiesAccelerated'],
    'allergies.ts': ['Allergies', 'AllergiesAccelerated'],
    'analytics.ts': [],
    'api.ts': fullTestRun,
    'App.test.tsx': [],
    'appointments.json': appointmentsArray,
    'appointments.ts': appointmentsArray,
    'appointmentsTestTime.json': appointmentsArray,
    'App.tsx': fullTestRun,
    'backButtonLabels.ts': [],
    'claims.json': claimsAndAppealsArray,
    'claims.ts': claimsAndAppealsArray,
    'common.ts': fullTestRun,
    'contactInformation.json': contactInfoArray,
    'countries.ts': ['ContactInformation'],
    'debts.ts': debtsArray,
    'debts.json': debtsArray,
    'decisionLetters.json': ['DecisionLetters'],
    'decisionLetters.ts': ['DecisionLetters'],
    'demographics.ts': demographicsArray,
    'disabilityRating.json': disabilityVeteranArray,
    'disabilityRating.ts': disabilityVeteranArray,
    'documentTypes.ts': [],
    'errors.ts': [],
    'getAuthorizedServices.json': authorizedServicesArray,
    'getFacilitiesInfo.json': ['Cerner'],
    'getFacilitiesInfoCerner.json': ['Cerner'],
    'gmtTimezones.ts': appointmentsArray,
    'labsAndTests.json': ['LabsAndTests'],
    'labsAndTests.ts': ['LabsAndTests'],
    'letters.json': ['VALetters'],
    'letters.ts': ['VALetters'],
    'linking.tsx': [],
    'medicalCopays.ts': medicalCopaysArray,
    'medicalCopays.json': medicalCopaysArray,
    'militaryPostOffices.ts': ['ContactInformation'],
    'militaryStates.ts': ['ContactInformation'],
    'namespaces.ts': [],
    'notifications.json': notificationsArray,
    'notifications.ts': notificationsArray,
    'payments.json': ['Payments'],
    'payments.ts': ['Payments'],
    'personalInformation.json': demographicsArray,
    'prescriptions.json': ['Prescriptions'],
    'profile.json': profileScreenArray,
    'profile.ts': profileScreenArray,
    'screens.ts': fullTestRun,
    'secureMessaging.json': ['Messages'],
    'secureMessaging.ts': ['Messages'],
    'states.ts': ['ContactInformation'],
    'store.ts': [],
    'travelPay.ts': ['TravelPay', 'TravelPayClaims'],
    'users.ts': [],
    'utils.ts': [],
    'vaccine.json': ['VaccineRecords'],
    'vaccine.ts': ['VaccineRecords'],
    'whatsNew.ts': [],
  },
}

module.exports = detoxMapping
