// Reusable array variables for detox mapping

// Full test run - used by components, slices, translations, utils
const fullTestRun = [
  'Allergies',
  'Appeals',
  'AppealsExpanded',
  'Appointments',
  'AppointmentsExpanded',
  'AppointmentsTestTime',
  'AvailabilityFramework',
  'Cerner',
  'Claims',
  'ContactInformation',
  'DecisionLetters',
  'DirectDeposit',
  'DisabilityRatings',
  'HomeScreen',
  'LabsAndTests',
  'LoginScreen',
  'Messages',
  'MilitaryInformation',
  'Navigation',
  'Onboarding',
  'Payments',
  'PersonalInformationScreen',
  'Prescriptions',
  'ProfileScreen',
  'PushNotifications',
  'SettingsScreen',
  'SignIn',
  'TravelPay',
  'VaccineRecords',
  'VALetters',
  'VeteransCrisisLine',
  'VeteranStatusCard',
]

// Authorized services array
const authorizedServicesArray = [
  'Appeals',
  'AppealsExpanded',
  'Appointments',
  'AppointmentsExpanded',
  'AppointmentsTestTime',
  'Claims',
  'DirectDeposit',
  'DisabilityRatings',
  'PersonalInformationScreen',
  'VALetters',
  'MilitaryInformation',
  'Payments',
  'Prescriptions',
  'Messages',
  'VeteranStatusCard',
]

// Commonly reused smaller arrays
const claimsAndAppealsArray = ['Appeals', 'AppealsExpanded', 'Claims']
const contactInfoArray = ['ContactInformation', 'VALetters']
const demographicsArray = ['PersonalInformationScreen', 'VeteranStatusCard', 'HomeScreen', 'ProfileScreen']
const disabilityVeteranArray = ['DisabilityRatings', 'VeteranStatusCard']
const appointmentsArray = ['Appointments', 'AppointmentsExpanded', 'AppointmentsTestTime', 'TravelPay']
const profileScreenArray = [
  'ProfileScreen',
  'ContactInformation',
  'MilitaryInformation',
  'PersonalInformationScreen',
  'SettingsScreen',
  'VALetters',
  'Payments',
]
const healthScreenArray = [
  'Appointments',
  'AppointmentsExpanded',
  'AppointmentsTestTime',
  'Cerner',
  'Prescriptions',
  'Messages',
  'VaccineRecords',
]
const homeScreenArray = ['HomeScreen', 'ProfileScreen', 'VeteranStatusCard']
const benefitsScreenArray = ['DisabilityRatings', 'Claims', 'Appeals', 'VALetters']

const detoxMapping = {
  directory: {
    allergies: ['Allergies'],
    authorizedServices: authorizedServicesArray,
    claimsAndAppeals: claimsAndAppealsArray,
    contactInformation: contactInfoArray,
    decisionLetters: ['DecisionLetters'],
    demographics: demographicsArray,
    directDeposit: ['DirectDeposit'],
    disabilityRating: disabilityVeteranArray,
    facilities: ['Cerner'],
    labsAndTests: ['LabsAndTests'],
    letters: ['VALetters'],
    militaryService: ['MilitaryInformation', 'VeteranStatusCard'],
    notifications: ['SettingsScreen', 'PushNotifications'],
    payments: ['Payments'],
    personalInformation: demographicsArray,
    prescriptions: ['Prescriptions'],
    secureMessaging: ['Messages'],
    types: fullTestRun,
    vaccines: ['VaccineRecords'],
    components: fullTestRun,
    LoginScreen: ['LoginScreen'],
    AppealDetailsScreen: ['Appeals', 'AppealsExpanded'],
    ClaimDetailsScreen: ['Claims'],
    ClaimLettersScreen: ['Claims'],
    ClaimsAndAppealsListView: claimsAndAppealsArray,
    ClaimsHistoryScreen: ['Claims'],
    NeedHelpData: claimsAndAppealsArray,
    NoClaimsAndAppeals: claimsAndAppealsArray,
    NoClaimsAndAppealsAccess: claimsAndAppealsArray,
    ClaimsScreen: claimsAndAppealsArray,
    DisabilityRatingsScreen: disabilityVeteranArray,
    Letters: ['VALetters'],
    Appointments: appointmentsArray,
    CernerAlert: ['Cerner'],
    HealthHelp: ['Cerner'],
    Pharmacy: ['Prescriptions'],
    SecureMessaging: ['Messages'],
    Vaccines: ['VaccineRecords'],
    ContactVAScreen: ['HomeScreen'],
    ProfileScreen: profileScreenArray,
    ContactInformationScreen: contactInfoArray,
    MilitaryInformationScreen: ['MilitaryInformation', 'VeteranStatusCard'],
    PersonalInformationScreen: demographicsArray,
    VeteransCrisisLineScreen: ['VeteransCrisisLine', 'SignIn'],
    VeteranStatusScreen: ['VeteranStatusCard'],
    OnboardingCarousel: ['Onboarding'],
    RequestNotifications: ['Onboarding'],
    DirectDepositScreen: ['DirectDeposit'],
    PaymentHistory: ['Payments'],
    SplashScreen: ['Onboarding', 'LoginScreen'],
    BenefitsScreen: benefitsScreenArray,
    HealthScreen: healthScreenArray,
    HomeScreen: homeScreenArray,
    SettingsScreen: ['SettingsScreen'],
    PaymentsScreen: ['Payments', 'DirectDeposit'],
    slices: fullTestRun,
    translations: fullTestRun,
    travelPay: ['TravelPay'],
    utils: fullTestRun,
    device: [],
    BiometricsPreferenceScreen: [],
    SyncScreen: [],
    WebviewScreen: [],
    styles: [],
    TravelPay: ['TravelPay'],
    benjaminAdams: [],
    claraJefferson: [],
    kimberlyWashington: [],
    dennisMadison: [],
  },
  files: {
    'allergies.ts': ['Allergies'],
    'labsAndTests.ts': ['LabsAndTests'],
    'accounts.ts': ['DirectDeposit'],
    'appointments.ts': appointmentsArray,
    'claims.ts': ['Claims', 'Appeals', 'AppealsExpanded'],
    'common.ts': fullTestRun,
    'countries.ts': ['ContactInformation'],
    'gmtTimezones.ts': ['Appointments', 'AppointmentsExpanded', 'AppointmentsTestTime'],
    'militaryPostOffices.ts': ['ContactInformation'],
    'militaryStates.ts': ['ContactInformation'],
    'screens.ts': fullTestRun,
    'secureMessaging.ts': ['Messages'],
    'states.ts': ['ContactInformation'],
    'appointmentsTestTime.json': ['AppointmentsTestTime'],
    'appointments.json': ['Appointments', 'AppointmentsExpanded'],
    'claims.json': ['Claims', 'Appeals', 'AppealsExpanded'],
    'contactInformation.json': contactInfoArray,
    'decisionLetters.json': ['DecisionLetters'],
    'disabilityRating.json': ['DisabilityRatings'],
    'getAuthorizedServices.json': authorizedServicesArray,
    'getFacilitiesInfo.json': ['Cerner'],
    'getFacilitiesInfoCerner.json': ['Cerner'],
    'letters.json': ['VALetters'],
    'notifications.json': ['SettingsScreen', 'PushNotifications'],
    'payments.json': ['Payments'],
    'personalInformation.json': demographicsArray,
    'prescriptions.json': ['Prescriptions'],
    'profile.json': profileScreenArray,
    'secureMessaging.json': ['Messages'],
    'vaccine.json': ['VaccineRecords'],
    'decisionLetters.ts': ['DecisionLetters'],
    'demographics.ts': demographicsArray,
    'disabilityRating.ts': ['DisabilityRatings'],
    'letters.ts': ['VALetters'],
    'notifications.ts': ['SettingsScreen', 'PushNotifications'],
    'payments.ts': ['Payments'],
    'profile.ts': profileScreenArray,
    'travelPay.ts': ['TravelPay'],
    'vaccine.ts': ['VaccineRecords'],
    'api.ts': fullTestRun,
    'App.tsx': fullTestRun,
    'App.test.tsx': [],
    'analytics.ts': [],
    'backButtonLabels.ts': [],
    'documentTypes.ts': [],
    'errors.ts': [],
    'linking.tsx': [],
    'namespaces.ts': [],
    'store.ts': [],
    'utils.ts': [],
    'allergies.json': ['Allergies'],
    'labsAndTests.json': ['LabsAndTests'],
    'users.ts': [],
  },
}

module.exports = detoxMapping
