name: '[Admin] Add pull request to project board'
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
jobs:
  add-to-project:
    name: Add PR to project board
    if: ${{ github.event.pull_request.base.ref == 'develop' && !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.FLAGSHIP_MOBILE_APP_ID }}
          private-key: ${{ secrets.FLAGSHIP_MOBILE_APP_PRIVATE_KEY }}
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/department-of-veterans-affairs/projects/1633
          github-token: ${{ steps.generate_token.outputs.token }}
