name: "[Admin] Add PR to Project Board"
on:
    pull_request_review:
        types: [submitted, edited]
jobs:
    add-to-project:
        name: Add pull request to project
        if: ${{ github.event.pull_request.base.ref == 'develop' }}
        runs-on: ubuntu-latest
        steps:
        - uses: actions/add-to-project
          with:
            project-url: https://github.com/orgs/department-of-veterans-affairs/projects/1633
            github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
