name: Update Slack Channel Description from PagerDuty

on:
  # schedule:
  #   - cron: '0 13 * * 1' # Monday at 9AM EST (13:00 UTC)
  # workflow_dispatch:
  push:

env:
  PAGERDUTY_API_TOKEN: ${{ secrets.PD_KEY }}
  PAGERDUTY_SCHEDULE_ID: "P841QDE"
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
  SLACK_CHANNEL_ID: "C07JWHB0U86"

jobs:
  update-slack-description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install axios dayjs

      - name: Create update script
        run: |
          mkdir -p scripts
          cat << 'EOF' > scripts/updateSlackFromPagerDuty.js
          const axios = require('axios');
          const dayjs = require('dayjs');

          async function main() {
            const PAGERDUTY_API_TOKEN = process.env.PAGERDUTY_API_TOKEN;
            const PAGERDUTY_SCHEDULE_ID = process.env.PAGERDUTY_SCHEDULE_ID;
            const SLACK_BOT_TOKEN = process.env.SLACK_BOT_TOKEN;
            const SLACK_CHANNEL_ID = process.env.SLACK_CHANNEL_ID;

            const start = dayjs().startOf('day').toISOString();
            const end = dayjs().endOf('day').toISOString();

            // Get on-call user for today
            const response = await axios.get(
              \`https://api.pagerduty.com/schedules/\${PAGERDUTY_SCHEDULE_ID}/users\`,
              {
                headers: {
                  Authorization: \`Token token=\${PAGERDUTY_API_TOKEN}\`,
                  Accept: 'application/vnd.pagerduty+json;version=2',
                },
                params: {
                  since: start,
                  until: end,
                },
              }
            );

            if (!response.data.users || response.data.users.length === 0) {
              throw new Error('No on-call user found.');
            }

            const user = response.data.users[0];
            const onCallName = user.summary;

            const topic = \`This week's on-call: \${onCallName}\`;

            // Update Slack channel topic
            await axios.post(
              'https://slack.com/api/conversations.setTopic',
              new URLSearchParams({
                channel: SLACK_CHANNEL_ID,
                topic,
              }),
              {
                headers: {
                  Authorization: \`Bearer \${SLACK_BOT_TOKEN}\`,
                  'Content-Type': 'application/x-www-form-urlencoded',
                },
              }
            );

            console.log('Updated Slack topic to:', topic);
          }

          main().catch(err => {
            console.error(err);
            process.exit(1);
          });
          EOF

      - name: Run update script
        run: node scripts/updateSlackFromPagerDuty.js
