# workflow to check that PR does not break any Apple App Store max file or max character limits
name: "App Store requirement checks"

on:
  pull_request:
    branches:
      - main
      - develop
      - 'release/v**'
    paths:
      - "VAMobile/ios/fastlane/metadata/en-US/**"
      - "VAMobile/ios/fastlane/screenshots/**"

jobs:
  check_ios_ipad_pro2_images:
    uses: ./.github/workflows/check_max_size.yml
    with:
      max_size: 10
      working_dir: VAMobile/ios/fastlane/screenshots/en-US
      counting_function: find . -maxdepth 1 -name "ipadPro2*" -printf '.' | wc -m
  check_ios_ipad_pro13_images:
    uses: ./.github/workflows/check_max_size.yml
    with:
      max_size: 10
      working_dir: VAMobile/ios/fastlane/screenshots/en-US
      counting_function: find . -maxdepth 1 -name "ipadPro13*" -printf '.' | wc -m
  check_ios_ipad_pro129_images:
    uses: ./.github/workflows/check_max_size.yml
    with:
      max_size: 10
      working_dir: VAMobile/ios/fastlane/screenshots/en-US
      counting_function: find . -maxdepth 1 -name "ipadPro12*" -printf '.' | wc -m
  check_ios_iphone55_images:
    uses: ./.github/workflows/check_max_size.yml
    with:
      max_size: 10
      working_dir: VAMobile/ios/fastlane/screenshots/en-US
      counting_function: find . -maxdepth 1 -name "phone5*" -printf '.' | wc -m
  check_ios_iphone67_images:
    uses: ./.github/workflows/check_max_size.yml
    with:
      max_size: 10
      working_dir: VAMobile/ios/fastlane/screenshots/en-US
      counting_function: find . -maxdepth 1 -name "iphone6*" -printf '.' | wc -m
  check_ios_description:
    uses: ./.github/workflows/check_max_size.yml
    with:
      max_size: 4000
      working_dir: VAMobile/ios/fastlane/metadata/en-US
      counting_function: wc -c description.txt | awk '{print $1}'
  check_ios_release_notes:
    uses: ./.github/workflows/check_max_size.yml
    with:
      max_size: 4000
      working_dir: VAMobile/ios/fastlane/metadata/en-US
      counting_function: wc -c release_notes.txt | awk '{print $1}'
  check_ios_keyword:
    uses: ./.github/workflows/check_max_size.yml
    with:
      max_size: 1000
      working_dir: VAMobile/ios/fastlane/metadata/en-US
      counting_function: wc -c keywords.txt | awk '{print $1}'
  check_ios_title:
    uses: ./.github/workflows/check_max_size.yml
    with:
      max_size: 50
      working_dir: VAMobile/ios/fastlane/metadata/en-US
      counting_function: wc -c title.txt | awk '{print $1}'
