name: "App Store requirement checks"

on:
  pull_request:

jobs:
  check_max_android_phone_screenshots:
    uses: ./.github/workflows/max_files_check.yml
    with:
      max_files: 8
      working_dir: VAMobile/android/fastlane/metadata/android/en-US/images/phoneScreenshots
  check_max_android_seven_inch_screenshots:
    uses: ./.github/workflows/max_files_check.yml
    with:
      max_files: 8
      working_dir: VAMobile/android/fastlane/metadata/android/en-US/images/sevenInchScreenshots
  check_android_description:
    uses: ./.github/workflows/check_max_size.yml
    with:
      max_files: 4000
      working_dir: VAMobile/android/fastlane/metadata/android/en-US
      file_counting_function: wc -c full-description.txt | awk '{print $1}'
  check_ios_images:
    uses: ./.github/workflows/check_max_size.yml
    with:
      max_files: 10
      working_dir: VAMobile/ios/fastlane/screenshots/en-US
      file_counting_function: find . -maxdepth 1 -name "ipadPro2nd*" -printf '.' | wc -m
  check_ios_description:
    uses: ./.github/workflows/check_max_size.yml
    with:
      max_files: 4000
      working_dir: VAMobile/ios/fastlane/metadata/en-US
      file_counting_function: wc -c description.txt | awk '{print $1}'
