# Workflow that labels a pr with FE Changes requested and removes other labels when changes are requested
name: "[Github Management] Changes Requested"

on:
  pull_request_review:
    types: [submitted]

jobs:
  changes_requested:
    if: github.event.review.state != 'APPROVED'
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Remove FE-Needs Review
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: ${{ github.event.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ["FE-Needs%20Review"]
            })
      
      - name: Remove FE-With QA
        if: failure() || success()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: ${{ github.event.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ["FE-With%20QA"]
            })

      - name: Add the changes requested label
        if: failure() || success()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
            issue_number: ${{ github.event.number }},
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ["FE-Changes%20Requested"]
            })
