# Workflow that labels a pr with FE Changes requested and removes other labels when changes are requested
name: "[Github Management] Changes Requested"

on:
  pull_request_review:
    types: [submitted]

jobs:
  changes_requested:
    if: github.event.review.state != 'APPROVED'
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Remove all existing labels
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.removeLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })

      - name: Add the changes requested label
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ["FE-Changes%20Requested"]
            })
