name: "[Utils] Check Maintenance Windows"

on:
  push:
  workflow_dispatch:
  # schedule:
  # 04:00 UTC, 12:00AM ET, 9:00PM every day at Midnight
  # - cron: "00 4 * * *"

jobs:
  check_maintenance_windows:
    # id: maint_windows
    name: Checkout repo
    runs-on: ubuntu-latest
    outputs:
      python_output: ${{ steps.maint_windows.outputs.py_output }}
    defaults:
      run:
        working-directory: VAMobile
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            VAMobile/maintenance_windows.py
            VAMobile/requirements.txt
          token: ${{ secrets.GH_ACTIONS_PAT }}
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Check Maintenance Windows
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_PAT }}
          PAGERDUTY_API_KEY: ${{ secrets.PD_KEY }}
        run: |
          echo "Installing dependencies..."
          pip install -r requirements.txt
          echo "Running Script to check maintenance windows..."
          py_output=$(python3 maintenance_windows.py)
          echo "py_output=$py_output >> $GITHUB_OUTPUT"

  start_slack_thread:
    name: Start Slack thread
    needs: check_maintenance_windows
    if: ${{ success() }}
    uses: ./.github/workflows/start_slack_thread.yml
    secrets: inherit
    with:
      channel_name: va-mobile-sandbox
      message: "Maintenance Windows updated! \n ${{ needs.check_maintenance_windows.outputs.python_output }} See :thread: or <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|workflow run> for results."

  #   name: Notify if windows update
  #   needs: check_maintenance_windows
  #   if: ${{ success() }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Notify Slack on update success
  #       env:
  #         SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
  #       run: |
  #         curl -X POST \
  #              -H 'Authorization: Bearer '"$SLACK_API_TOKEN" \
  #              -H 'Content-type: application/json' \
  #              -d '{"channel": "va-mobile-sandbox", "text": "Maintenance window update success!" , "thread_ts": "${{ needs.start_slack_thread.outputs.thread_ts }}"}' \ # final channel will be va-mobile-app
  #              https://slack.com/api/chat.postMessage
  #
  # notify_update_failure:
  #   name: Notify if windows fail to update
  #   needs: check_maintenance_windows
  #   if: ${{ failure() }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Notify Slack on update failure
  #       env:
  #         SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
  #       run: |
  #         curl -X POST \
  #              -H 'Authorization: Bearer '"$SLACK_API_TOKEN" \
  #              -H 'Content-type: application/json' \
  #              -d '{"channel": "va-mobile-sandbox", "text": "Maintenance Windows failed to update" , "thread_ts": "${{ needs.start_slack_thread.outputs.thread_ts }}"}' \ # final channel will be va-mobile-app
  #              https://slack.com/api/chat.postMessage
  #
