name: "[Utils] Check Maintenance Windows"

on:
  push:
  workflow_dispatch:
  # schedule:
  # 04:00 UTC, 12:00AM ET, 9:00PM every day at Midnight
  # - cron: "00 4 * * *"

jobs:
  check_maintenance_windows:
    name: Maintenance Window Update
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: VAMobile
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            VAMobile/maintenance_windows.py
            VAMobile/requirements.txt
          token: ${{ secrets.GH_ACTIONS_PAT }}
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Check Maintenance Windows
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_PAT }}
          PAGERDUTY_API_KEY: ${{ secrets.PD_KEY }}
        run: |
          echo "Installing dependencies..."
          pip install -r requirements.txt
          echo "Running Script to check maintenance windows..."
          python3 maintenance_windows.py

  start_slack_thread_success:
    name: Start Slack thread
    needs: check_maintenance_windows
    if: ${{ success() }}
    uses: ./.github/workflows/start_slack_thread.yml
    secrets: inherit
    with:
      channel_name: va-mobile-sandbox
      message: "Maintenance Windows update success! \n See <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|workflow run> for results. \n <https://dsva.pagerduty.com/service-directory/maintenance-windows?Teams-search=mob&team_ids=PSACBVG|Mobile Maintenance Windows>"

  start_slack_thread_failure:
    name: Start Slack thread
    needs: check_maintenance_windows
    if: ${{ failure() }}
    uses: ./.github/workflows/start_slack_thread.yml
    secrets: inherit
    with:
      channel_name: va-mobile-sandbox
      message: "Maintenance Windows update failed! \n  See <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|workflow run> for results. \n <https://dsva.pagerduty.com/service-directory/maintenance-windows?Teams-search=mob&team_ids=PSACBVG|Mobile Maintenance Windows>"
