name: "[TestRail] Create TestRail Milestone"

on:
  workflow_call:
    outputs:
      milestoneId:
        value: ${{ jobs.create_milestone.outputs.milestoneId }}
    secrets:
      TEST_RAIL_USER:
        description: "TestRail robot userid"
        required: true
      TEST_RAIL_KEY:
        description: "TestRail api key"
        required: true

jobs:
  create_milestone:
    outputs:
      milestoneId: ${{ steps.add_milestone.outputs.milestone }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Add new sprint milestone in TestRail'
        id: add_milestone
        run: |
          dateRange="$(date '+%B %-d') - $(date -d '+13 days' '+%B %-d')"
          id=$(curl -X POST -H 'Content-Type: application/json' \
            -u "${{secrets.TEST_RAIL_USER}}:${{secrets.TEST_RAIL_KEY}}" \
            "https://dsvavsp.testrail.io//index.php?/api/v2/add_milestone/29" \
            -d '{"name": "Sprint: '"${dateRange}"'", "description": "Milestone for all testing performed during Sprint: '"${dateRange}"'", "start_on": '$(date +%s)', "due_on": '$(date -d '+13 days' '+%s')' }' |
            jq '.id')
          echo "id is $id"
          curl -X POST -H 'Content-Type: application/json' \
            -u "${{secrets.TEST_RAIL_USER}}:${{secrets.TEST_RAIL_KEY}}" \
            "https://dsvavsp.testrail.io//index.php?/api/v2/update_milestone/${id}" \
            -d '{"is_started":1}'
          echo ""
          echo "::set-output name=milestone::${id}"
