name: Manual Test Simple

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: |
          echo "This is a manual test workflow"
          echo "Current time: $(date)"
