name: '[Test] Manual Validation Test'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        default: staging
        type: choice
        options:
          - staging
          - production
      lane:
        description: Lane
        required: true
        default: qa
        type: choice
        options:
          - qa
          - review
          - release

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Test validation
        run: |
          echo "Testing environment: ${{ inputs.environment }}"
          echo "Testing lane: ${{ inputs.lane }}"
          
          # Test the validation logic
          declare -A valid_combinations
          valid_combinations["production,review"]=1
          valid_combinations["staging,qa"]=1
          
          combination="${{ inputs.environment }},${{ inputs.lane }}"
          
          if [[ ${valid_combinations[$combination]} ]]; then
            echo "✅ Valid combination: $combination"
          else
            echo "❌ Invalid combination: $combination"
            exit 1
          fi
