name: 'Check max files in directory'

on:
  workflow_call:
    inputs:
      working_dir:
        required: true
        type: string
      max_files:
        required: true
        type: string

jobs:
  check_max_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          if [[ $(ls | wc -l) -gt ${{ inputs.max_files }} ]]
          then
            echo "PR exceeds app store limits on images in this directory"
            exit 1
          else
            echo "we are good here"
          fi
        working-directory: ${{ inputs.working_dir }}
