name: '[Code Quality] Check Native Android Builds'
description: 'This test has the opposite filter of native_build_check_android.yml so that required checks dont hang'

on:
  pull_request:
    paths:
      - "!VAMobile/android/**"

jobs:
  android_native_build:
    runs-on: ubuntu-latest
    name: Android Test Build
    uses: ./.github/workflows/native_build_check_android_reusable.yml
