# A skip workflow for iOS native checks.
# This workflow triggers when VAMobile/ios/** files are NOT modified.
# It reports success immediately to ensure that PRs do not hang if this
# status check is marked as "Required" in branch protection rules.

name: '[Code Quality] Check Native iOS Builds'

on:
  pull_request:
    paths:
      - '!VAMobile/ios/**'

jobs:
  ios_native_build:
    name: iOS Test Build
    runs-on: ubuntu-latest
    steps:
      - run: echo "PASS -- No native ios files updated."
