name: '[Code Quality] Check Native Android Builds'
description: 'This is a reusable workflow so that required checks work correctly. see https://github.com/orgs/community/discussions/36680'

on:
  workflow_call:

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - run: echo "PASS -- No native android files updated."
