# A skip workflow for Android native checks.
# This workflow triggers when VAMobile/android/** files are NOT modified.
# It reports success immediately to ensure that PRs do not hang if this
# status check is marked as "Required" in branch protection rules.

name: '[Code Quality] Check Native Android Builds'

on:
  pull_request:
    paths:
      - '!VAMobile/android/**'

jobs:
  android_native_build:
    name: Android Test Build
    runs-on: ubuntu-latest
    steps:
      - run: echo "PASS -- No native android files updated."
