name: '[Utils] Onboarding'

on:
  issues:
    types: [labeled]

jobs:
  start-worlflow:
    if: contains(github.event.issue.labels.*.name, 'onboarding') && !contains(github.event.issue.labels.*.name, 'processed') && !contains(github.event.issue.labels.*.name, 'complete')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Step 1
        run: echo ${{ github.event.issue }}
  # initiate-onboarding:
  #   if: contains(github.event.issue.labels.*.name, 'onboarding') && !contains(github.event.issue.labels.*.name, 'processed') && !contains(github.event.issue.labels.*.name, 'complete')
  #   name: Start Slack thread
  #   uses: ./.github/workflows/start_slack_thread.yml
  #   secrets: inherit
  #   with:
  #     channel_name: va-mobile-build-alerts
  #     message: ':tada: A new onboarding request has been initiated'
