name: "Build PR Merged"

on:
  push:
    branches:
      - feature/pr-test
  pull_request:
    types: [ closed ]
    branches:
      - feature/pr-test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Do stuff
        run: |
          echo ${{github.ref}}
          echo ${{github.head_ref}}
          echo ${{github.base_ref}}
