name: "[Admin] Flagship Mobile Alerts Weekly On-Call Assignment"

on:
  push:
  workflow_dispatch:
  schedule:
    # Run every Monday at 8:30 AM EST (1:30 PM UTC)
    - cron: '30 13 * * 1'

env:
  SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}

jobs:
  assign-oncall:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Set static on-call rotation through 2025
        id: select-oncall
        run: |
          # Static rotation order
          declare -A GITHUB_TO_SLACK=(
            ["timwright12"]="U08H8A5Q00J"
            ["ryan-mcneil"]="U051N9T603X"
            ["SMLuthi"]="U9YP3N7C7"
            ["jbergman-oddball"]="U08FHQEA8P7"
          )
          ROTATION=("timwright12" "ryan-mcneil" "SMLuthi" "jbergman-oddball")
          # Get current date
          TODAY=$(date -u +%Y-%m-%d)
          # List of Mondays from this week through end of 2025
          START_DATE=$(date -u -d "$TODAY" +%Y-%m-%d)
          END_DATE="2025-12-29"
          # Find the next Monday (or today if Monday)
          DOW=$(date -u -d "$START_DATE" +%u)
          if [ "$DOW" -ne 1 ]; then
            # Not Monday, find next Monday
            NEXT_MONDAY=$(date -u -d "$START_DATE +$(( (8 - DOW) % 7 )) days" +%Y-%m-%d)
          else
            NEXT_MONDAY="$START_DATE"
          fi
          # Build schedule
          SCHEDULE=()
          d="$NEXT_MONDAY"
          i=0
          while [[ "$d" < "$END_DATE" || "$d" == "$END_DATE" ]]; do
            SCHEDULE+=("$d:${ROTATION[$((i%4))]}")
            d=$(date -u -d "$d +7 days" +%Y-%m-%d)
            ((i++))
          done
          # Find this week's on-call
          THIS_WEEK=$(date -u +%Y-%m-%d)
          # Find the most recent Monday <= today
          DOW=$(date -u -d "$THIS_WEEK" +%u)
          if [ "$DOW" -ne 1 ]; then
            THIS_MONDAY=$(date -u -d "$THIS_WEEK -$((DOW-1)) days" +%Y-%m-%d)
          else
            THIS_MONDAY="$THIS_WEEK"
          fi
          ONCALL_PERSON=""
          for entry in "${SCHEDULE[@]}"; do
            week_date="${entry%%:*}"
            person="${entry##*:}"
            if [ "$week_date" == "$THIS_MONDAY" ]; then
              ONCALL_PERSON="$person"
              break
            fi
          done
          if [ -z "$ONCALL_PERSON" ]; then
            echo "No on-call person found for this week ($THIS_MONDAY)" >&2
            exit 1
          fi
          SLACK_USER_ID="${GITHUB_TO_SLACK[$ONCALL_PERSON]}"
          if [ -z "$SLACK_USER_ID" ]; then
            SLACK_MENTION="@$ONCALL_PERSON"
          else
            SLACK_MENTION="<@$SLACK_USER_ID>"
          fi
          echo "oncall_person=$ONCALL_PERSON" >> $GITHUB_OUTPUT
          echo "slack_mention=$SLACK_MENTION" >> $GITHUB_OUTPUT
          echo "week_date=$THIS_MONDAY" >> $GITHUB_OUTPUT
          echo "Selected on-call person: $ONCALL_PERSON for week of $THIS_MONDAY"
      - name: Get Slack channel ID
        id: get-channel
        run: |
          CHANNEL_NAME="va-mobile-sandbox"
          fetch_page() {
            last_response=$(curl -X GET -H 'Authorization: Bearer '"$SLACK_API_TOKEN"' ' \
            -H 'Content-type: application/x-www-form-urlencoded' \
            https://slack.com/api/conversations.list\?limit=1000\&cursor=$cursor | jq .)
          }
          get_id() {
            id=$(jq '.channels[] | .name as $data | select($data == "'$CHANNEL_NAME'").id' <<< $last_response)
          }
          get_cursor() {
            cursor=$(jq '.response_metadata.next_cursor' <<< $last_response)
          }
          id=""
          cursor=""
          last_response=""
          fetch_page
          get_id
          while [[ -z "$id" ]]
          do
            get_cursor
            fetch_page
            get_id
          done
          echo "channel_id=${id}" >> $GITHUB_OUTPUT
      - name: Send Slack notification
        run: |
          SLACK_MENTION="${{ steps.select-oncall.outputs.slack_mention }}"
          CHANNEL_ID="${{ steps.get-channel.outputs.channel_id }}"
          URL="https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/BackEnd/Monitoring/OnCallProcedure/"
          echo "Sending Slack notification..."
          curl -X POST \
            -H "Authorization: Bearer $SLACK_API_TOKEN" \
            -H "Content-type: application/json; charset=utf-8" \
            -d "{\"channel\":\"$CHANNEL_ID\",\"text\":\"🚨 *On-Call Alert rotation this week: $SLACK_MENTION*\\n\\nOn call procedure: <$URL>\"}" \
            https://slack.com/api/chat.postMessage
      - name: Update channel topic
        run: |
          SLACK_MENTION="${{ steps.select-oncall.outputs.slack_mention }}"
          CHANNEL_ID="${{ steps.get-channel.outputs.channel_id }}"
          TOPIC_TEXT="Alert rotation this week: $SLACK_MENTION\nOn call procedure: https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/BackEnd/Monitoring/OnCallProcedure/"
          echo "Updating channel topic..."
          curl -X POST \
            -H "Authorization: Bearer $SLACK_API_TOKEN" \
            -H "Content-type: application/json; charset=utf-8" \
            -d "{\"channel\":\"$CHANNEL_ID\",\"topic\":\"$TOPIC_TEXT\"}" \
            https://slack.com/api/conversations.setTopic
