name: Setup Node Environment

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
        default: 'staging'
      ios:
        required: true
        type: boolean
        default: false
jobs:
  setup_env:
    runs-on: ${{ ios && 'macos-latest' || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: 'VAMobile/yarn.lock'
      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive
