name: 'Simple Manual Test'

on:
  workflow_dispatch:
    inputs:
      test_message:
        description: 'Test message'
        required: true
        default: 'Hello World'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: |
          echo "Message: ${{ inputs.test_message }}"
