---
name: Lint Them All

on: # yamllint disable-line rule:truthy
  push:
  # pull_request: null

defaults:
  run:
    working-directory: va-mobile-app
permissions:
  contents: read

jobs:
  # lint:
  # Super-linter workflow running in check only mode
  # See https://github.com/super-linter/super-linter#get-started

  fix-lint-issues:
    permissions:
      # To write linting fixes
      contents: write
      # To write Super-linter status checks
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Super-Linter
        uses: super-linter/super-linter@v7.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_PAT }}
          LINTER_RULES_PATH: ".github/linters"
          YAML_CONFIG_FILE: ".github/linters/.yamllint.yml"
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_CHECKOV: false
          VALIDATE_CLANG_FORMAT: false
          VALIDATE_CPP: false
          VALIDATE_CSS: false
          VALIDATE_CSS_PRETTIER: false
          VALIDATE_ENV: false
          VALIDATE_GITLEAKS: false
          VALIDATE_GOOGLE_JAVA_FORMAT: false
          VALIDATE_GROOVY: false
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JAVASCRIPT_PRETTIER: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JAVA: false
          VALIDATE_BASH: false
          VALIDATE_JSCPD: false
          VALIDATE_JSON: false
          VALIDATE_JSON_PRETTIER: false
          VALIDATE_KOTLIN: false
          VALIDATE_MARKDOWN: false
          VALIDATE_MARKDOWN_PRETTIER: false
          VALIDATE_NATURAL_LANGUAGE: false
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_PYTHON_PYLINT: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_PYTHON_MYPY: false
          VALIDATE_PYTHON_RUFF: false
          VALIDATE_PYTHON_PYINK: false
          VALIDATE_RUBY: false
          VALIDATE_SHELL_SHFMT: false
          VALIDATE_TSX: false
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_TYPESCRIPT_PRETTIER: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_DOCKER_HADOLINT: false
          VALIDATE_XML: false
          VALIDATE_YAML_PRETTIER: false

          # Set your fix mode variables to true
          # LINTER_RULES_PATH: .github/linters

          # To reuse the same Super-linter configuration that you use in the
          # lint job without duplicating it, see
          # https://github.com/super-linter/super-linter/blob/main/docs/run-linter-locally.md#share-environment-variables-between-environments
      # - name: Commit and push linting fixes
      # Run only on:
      # - Pull requests
      # - Not on the default branch
      # if: >
      #   github.event_name == 'pull_request' &&
      #   github.ref_name != github.event.repository.default_branch
      # uses: stefanzweifel/git-auto-commit-action@v5
      # with:
      #   branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
      #   commit_message: "chore: fix linting issues"
      #   commit_user_name: super-linter
      #   commit_user_email: super-linter@super-linter.dev
