name: Test get issues by label
on:
  push:
    branches:
      - feature/add-bugs-to-release-ticket

jobs:
  getIssues:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: get_issues
        with:
          route: GET /repos/{owner}/{repo}/issues
          owner: department-of-veterans-affairs
          repo: va-mobile-app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: printf "%s" "${{ steps.get_issues.outputs.data }}" > output.txt
      - name: Archive results
        uses: actions/upload-artifact@v2
        with:
          name: issues output
          path: outputs.txt
