name: '[Test] Testing workflow protections'

# Adapted from https://docusaurus.io/docs/deployment

on:
  workflow_dispatch:
  pull_request:
    branches: [develop]
    paths: 
      - VAMobile/src/components/**
      - VAMobile/documentation/**
      - VAMobile/src/utils/hooks.tsx

jobs:
  get-workflow-environment:
    runs-on: ubuntu-latest
    outputs:
      environment_name: ${{ steps.check-environment.outputs.env_name }}
    steps:
      - name: Check environment
        id: check-environment
        run: |
          if [[ ${{ github.event_name }} == 'workflow_dispatch' ]]; then
            echo env_name='Test' >> $GITHUB_OUTPUT
          else
            echo env_name='' >> $GITHUB_OUTPUT
          fi
  test-build:
    name: Test Build for Documentation
    runs-on: ubuntu-latest
    needs: [get-workflow-environment]
    environment: ${{ needs.get-workflow-environment.outputs.environment_name }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
          cache-dependency-path: VAMobile/yarn.lock
      - name: Test build
        working-directory: VAMobile
        run: |
          yarn install --frozen-lockfile
          cd documentation
          yarn install --frozen-lockfile
          yarn build
