name: Test get issues by label
on:
  push:
    branches:
      - feature/add-bugs-to-release-ticket

jobs:
  getIssues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "${{ secrets.GITHUB_TOKEN }}" >> token.txt
      - run: gh auth login --with-token < token.txt
      - run: |
          issues=$(gh issue list -l "sev-2" --jq 'map("|#\(.number)|\(.title)|") | join("\n") ' --json number,title)
          table="| Issue | Title | Notes |\n"
          table="${table}|-------|-------|-------|\n"
          echo "TABLE=${table}${issues}" >> $GITHUB_ENV
      - uses: JasonEtco/create-an-issue@v2
        with:
          filename: .github/ISSUE_TEMPLATE/test.md
        env:
          table: ${{ env.TABLE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
