name: Test get issues by label
on:
  push:
    branches:
      - feature/add-bugs-to-release-ticket

jobs:
  getIssues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "${{ secrets.GITHUB_TOKEN }}" >> token.txt
      - run: gh auth login --with-token < token.txt
      - run: |
          sev1=$(gh issue list -l "sev-1" --jq 'map("|#\(.number)|\(.title)|") | join("\n") ' --json number,title)
          sev2=$(gh issue list -l "sev-2" --jq 'map("|#\(.number)|\(.title)|") | join("\n") ' --json number,title)
          header='| Issue | Title | Notes |
          |-------|-------|-------|
          '
          table="${header}${sev1}${sev2}"
          echo 'TABLE<<EOF' >> $GITHUB_ENV
          echo "${table}" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - run: echo $TABLE
      - uses: JasonEtco/create-an-issue@v2
        with:
          filename: .github/ISSUE_TEMPLATE/test.md
        env:
          table: ${{ env.TABLE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
