name: 'reuse tester'

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
    outputs:
      devPrUrl:
        value: ${{jobs.reuse.outputs.devPrUrl}}
      releasePrUrl:
        value: ${{jobs.reuse.outputs.releasePrUrl}}

jobs:
  reuse:
    runs-on: ubuntu-latest
    outputs:
      devPrUrl: ${{steps.urls.outputs.dev}}
      releasePrUrl: ${{steps.urls.outputs.release}}
    steps:
      - run: echo "REUSE_TEST1=$(echo "reuse test 1")" >> $GITHUB_ENV
      - run: echo "REUSE_TEST2=$(echo "reuse test 2")" >> $GITHUB_ENV
      - id: urls
        run: |
          echo "::set-output name=dev::www.google.com}"
          echo "::set-output name=release::www.adhocteam.us"

