name: Lint Github Action files

on:
  push:
  # pull_request:
  #   branches: [main]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint:
    name: Let the Linting begin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .github/yamllint.yml

      - name: Run actionlint
        uses: rhysd/actionlint@v1.7.7
        with:
          args: -color -config-file .github/actionlint.yml
