name: Lint Github Action files
on:
  push:
  # pull_request:
  #   branches: [main]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install and run yamllint
        run: |
          pip install yamllint
          yamllint -c .github/yamllint.yml .
        shell: bash

      - name: Install and run actionlint
        run: |
          pip install "actionlint-py"
          actionlint -color -ignore 'shellcheck reported' -ignore 'action is too old to run' -ignore 'gobbing and word splitting' -ignore 'property .+ is not defined' .github/workflows/*.yml
        shell: bash
